import { schema } from "@mkja/o-data/schema";

export const microsoft_dynamics_crm_schema = schema({
  namespace: "Microsoft.Dynamics.CRM",
  alias: "mscrm",
  complextypes: {
    "AddToQueueResponse": {
      "QueueItemId": { type: 'Edm.Guid' },
    },
    "AddUserToRecordTeamResponse": {
      "AccessTeamId": { type: 'Edm.Guid' },
    },
    "BooleanManagedProperty": {
      "Value": { type: 'Edm.Boolean' },
      "CanBeChanged": { type: 'Edm.Boolean' },
      "ManagedPropertyLogicalName": { type: 'Edm.String' },
    },
    "CalculateTotalTimeIncidentResponse": {
      "TotalTime": { type: 'Edm.Int64' },
    },
    "RemoveUserFromRecordTeamResponse": {
      "AccessTeamId": { type: 'Edm.Guid' },
    },
    "SendEmailResponse": {
      "Subject": { type: 'Edm.String' },
    },
    "WhoAmIResponse": {
      "BusinessUnitId": { type: 'Edm.Guid' },
      "UserId": { type: 'Edm.Guid' },
      "OrganizationId": { type: 'Edm.Guid' },
    },
  },
  entitytypes: {
    "activitymimeattachment": {
      baseType: "crmbaseentity",
      properties: {
        "componentstate": { type: 'Edm.Int32' },
        "versionnumber": { type: 'Edm.Int64' },
        "filename": { type: 'Edm.String' },
        "overwritetime": { type: 'Edm.DateTimeOffset' },
        "subject": { type: 'Edm.String' },
        "filesize": { type: 'Edm.Int32' },
        "ismanaged": { type: 'Edm.Boolean' },
        "activitymimeattachmentid": { type: 'Edm.Guid' },
        "attachmentcontentid": { type: 'Edm.String' },
        "objecttypecode": { type: 'Edm.String' },
        "activitymimeattachmentidunique": { type: 'Edm.Guid' },
        "mimetype": { type: 'Edm.String' },
        "solutionid": { type: 'Edm.Guid' },
        "activitysubject": { type: 'Edm.String' },
        "attachmentnumber": { type: 'Edm.Int32' },
        "anonymouslink": { type: 'Edm.String' },
        "isfollowed": { type: 'Edm.Boolean' },
        "body": { type: 'Edm.String' },
        "body_binary": { type: 'Edm.Binary' },
        "objectid_email": { type: 'navigation', target: 'email', collection: false },
        "objectid_activitypointer": { type: 'navigation', target: 'activitypointer', collection: false },
      },
    },
    "activityparty": {
      baseType: "crmbaseentity",
      properties: {
        "donotfax": { type: 'Edm.Boolean' },
        "scheduledend": { type: 'Edm.DateTimeOffset' },
        "effort": { type: 'Edm.Double' },
        "addressusedemailcolumnnumber": { type: 'Edm.Int32' },
        "donotpostalmail": { type: 'Edm.Boolean' },
        "unresolvedpartyname": { type: 'Edm.String' },
        "ispartydeleted": { type: 'Edm.Boolean' },
        "versionnumber": { type: 'Edm.Int64' },
        "scheduledstart": { type: 'Edm.DateTimeOffset' },
        "instancetypecode": { type: 'Edm.Int32' },
        "externalidtype": { type: 'Edm.String' },
        "activitypartyid": { type: 'Edm.Guid' },
        "donotemail": { type: 'Edm.Boolean' },
        "exchangeentryid": { type: 'Edm.String' },
        "externalid": { type: 'Edm.String' },
        "participationtypemask": { type: 'Edm.Int32' },
        "addressused": { type: 'Edm.String' },
        "donotphone": { type: 'Edm.Boolean' },
        "partyid_queue": { type: 'navigation', target: 'queue', collection: false },
        "partyid_systemuser": { type: 'navigation', target: 'systemuser', collection: false },
        "activityid_email": { type: 'navigation', target: 'email', collection: false },
        "activityid_activitypointer": { type: 'navigation', target: 'activitypointer', collection: false },
        "partyid_contact": { type: 'navigation', target: 'contact', collection: false },
        "partyid_incident": { type: 'navigation', target: 'incident', collection: false },
        "activityid_incidentresolution": { type: 'navigation', target: 'incidentresolution', collection: false },
      },
    },
    "activitypointer": {
      baseType: "crmbaseentity",
      properties: {
        "senton": { type: 'Edm.DateTimeOffset' },
        "instancetypecode": { type: 'Edm.Int32' },
        "onholdtime": { type: 'Edm.Int32' },
        "description": { type: 'Edm.String' },
        "seriesid": { type: 'Edm.Guid' },
        "leftvoicemail": { type: 'Edm.Boolean' },
        "activitytypecode": { type: 'Edm.String' },
        "deliverylastattemptedon": { type: 'Edm.DateTimeOffset' },
        "exchangerate": { type: 'Edm.Decimal' },
        "isbilled": { type: 'Edm.Boolean' },
        "statuscode": { type: 'Edm.Int32' },
        "processid": { type: 'Edm.Guid' },
        "traversedpath": { type: 'Edm.String' },
        "scheduledstart": { type: 'Edm.DateTimeOffset' },
        "descriptionblobid": { type: 'Edm.Binary' },
        "activityadditionalparams": { type: 'Edm.String' },
        "subject": { type: 'Edm.String' },
        "scheduleddurationminutes": { type: 'Edm.Int32' },
        "sortdate": { type: 'Edm.DateTimeOffset' },
        "versionnumber": { type: 'Edm.Int64' },
        "community": { type: 'Edm.Int32' },
        "actualdurationminutes": { type: 'Edm.Int32' },
        "lastonholdtime": { type: 'Edm.DateTimeOffset' },
        "isworkflowcreated": { type: 'Edm.Boolean' },
        "scheduledend": { type: 'Edm.DateTimeOffset' },
        "isregularactivity": { type: 'Edm.Boolean' },
        "exchangeweblink": { type: 'Edm.String' },
        "ismapiprivate": { type: 'Edm.Boolean' },
        "formattedscheduledend": { type: 'Edm.DateTimeOffset' },
        "exchangeitemid": { type: 'Edm.String' },
        "stageid": { type: 'Edm.Guid' },
        "activityid": { type: 'Edm.Guid' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "postponeactivityprocessinguntil": { type: 'Edm.DateTimeOffset' },
        "formattedscheduledstart": { type: 'Edm.DateTimeOffset' },
        "descriptionblobid_name": { type: 'Edm.String' },
        "statecode": { type: 'Edm.Int32' },
        "actualstart": { type: 'Edm.DateTimeOffset' },
        "prioritycode": { type: 'Edm.Int32' },
        "deliveryprioritycode": { type: 'Edm.Int32' },
        "actualend": { type: 'Edm.DateTimeOffset' },
        "timezoneruleversionnumber": { type: 'Edm.Int32' },
        "utcconversiontimezonecode": { type: 'Edm.Int32' },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "regardingobjectid_contact": { type: 'navigation', target: 'contact', collection: false },
        "activity_pointer_email": { type: 'navigation', target: 'email', collection: true },
        "ActivityPointer_QueueItem": { type: 'navigation', target: 'queueitem', collection: true },
        "ownerid": { type: 'navigation', target: 'principal', collection: false },
        "owninguser": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "activity_pointer_activity_mime_attachment": { type: 'navigation', target: 'activitymimeattachment', collection: true },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "owningteam": { type: 'navigation', target: 'team', collection: false },
        "activitypointer_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "activity_pointer_incident_resolution": { type: 'navigation', target: 'incidentresolution', collection: true },
        "regardingobjectid_incident": { type: 'navigation', target: 'incident', collection: false },
      },
    },
    "contact": {
      baseType: "crmbaseentity",
      properties: {
        "educationcode": { type: 'Edm.Int32' },
        "donotemail": { type: 'Edm.Boolean' },
        "aging90": { type: 'Edm.Decimal' },
        "managerphone": { type: 'Edm.String' },
        "mobilephone": { type: 'Edm.String' },
        "shippingmethodcode": { type: 'Edm.Int32' },
        "address1_country": { type: 'Edm.String' },
        "address1_addresstypecode": { type: 'Edm.Int32' },
        "utcconversiontimezonecode": { type: 'Edm.Int32' },
        "annualincome_base": { type: 'Edm.Decimal' },
        "mspp_userpreferredlcid": { type: 'Edm.Int32' },
        "address1_composite": { type: 'Edm.String' },
        "address2_postofficebox": { type: 'Edm.String' },
        "address3_telephone1": { type: 'Edm.String' },
        "onholdtime": { type: 'Edm.Int32' },
        "creditlimit_base": { type: 'Edm.Decimal' },
        "address1_freighttermscode": { type: 'Edm.Int32' },
        "entityimageid": { type: 'Edm.Guid' },
        "statecode": { type: 'Edm.Int32' },
        "address2_postalcode": { type: 'Edm.String' },
        "entityimage_timestamp": { type: 'Edm.Int64' },
        "donotbulkemail": { type: 'Edm.Boolean' },
        "address3_shippingmethodcode": { type: 'Edm.Int32' },
        "stageid": { type: 'Edm.Guid' },
        "department": { type: 'Edm.String' },
        "governmentid": { type: 'Edm.String' },
        "address2_name": { type: 'Edm.String' },
        "address1_line1": { type: 'Edm.String' },
        "callback": { type: 'Edm.String' },
        "coop_kimcustomerid": { type: 'Edm.String' },
        "address2_line2": { type: 'Edm.String' },
        "traversedpath": { type: 'Edm.String' },
        "businesscardattributes": { type: 'Edm.String' },
        "address1_fax": { type: 'Edm.String' },
        "yomilastname": { type: 'Edm.String' },
        "gendercode": { type: 'Edm.Int32' },
        "merged": { type: 'Edm.Boolean' },
        "anniversary": { type: 'Edm.Date' },
        "marketingonly": { type: 'Edm.Boolean' },
        "address1_line2": { type: 'Edm.String' },
        "address2_addressid": { type: 'Edm.Guid' },
        "address2_composite": { type: 'Edm.String' },
        "birthdate": { type: 'Edm.Date' },
        "address1_shippingmethodcode": { type: 'Edm.Int32' },
        "address2_shippingmethodcode": { type: 'Edm.Int32' },
        "salutation": { type: 'Edm.String' },
        "home2": { type: 'Edm.String' },
        "company": { type: 'Edm.String' },
        "aging60_base": { type: 'Edm.Decimal' },
        "customersizecode": { type: 'Edm.Int32' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "fullname": { type: 'Edm.String' },
        "address2_latitude": { type: 'Edm.Double' },
        "preferredappointmenttimecode": { type: 'Edm.Int32' },
        "processid": { type: 'Edm.Guid' },
        "address1_primarycontactname": { type: 'Edm.String' },
        "isbackofficecustomer": { type: 'Edm.Boolean' },
        "description": { type: 'Edm.String' },
        "exchangerate": { type: 'Edm.Decimal' },
        "donotbulkpostalmail": { type: 'Edm.Boolean' },
        "paymenttermscode": { type: 'Edm.Int32' },
        "address3_addressid": { type: 'Edm.Guid' },
        "teamsfollowed": { type: 'Edm.Int32' },
        "address3_postofficebox": { type: 'Edm.String' },
        "territorycode": { type: 'Edm.Int32' },
        "address3_line2": { type: 'Edm.String' },
        "externaluseridentifier": { type: 'Edm.String' },
        "address1_telephone3": { type: 'Edm.String' },
        "donotphone": { type: 'Edm.Boolean' },
        "address3_country": { type: 'Edm.String' },
        "yomifirstname": { type: 'Edm.String' },
        "address1_postalcode": { type: 'Edm.String' },
        "address1_telephone2": { type: 'Edm.String' },
        "address3_stateorprovince": { type: 'Edm.String' },
        "spousesname": { type: 'Edm.String' },
        "address3_telephone2": { type: 'Edm.String' },
        "address1_longitude": { type: 'Edm.Double' },
        "participatesinworkflow": { type: 'Edm.Boolean' },
        "timezoneruleversionnumber": { type: 'Edm.Int32' },
        "address3_composite": { type: 'Edm.String' },
        "aging90_base": { type: 'Edm.Decimal' },
        "address2_primarycontactname": { type: 'Edm.String' },
        "contactid": { type: 'Edm.Guid' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "address2_addresstypecode": { type: 'Edm.Int32' },
        "coop_personalnumber": { type: 'Edm.String' },
        "address3_addresstypecode": { type: 'Edm.Int32' },
        "address2_line3": { type: 'Edm.String' },
        "address2_fax": { type: 'Edm.String' },
        "accountrolecode": { type: 'Edm.Int32' },
        "donotsendmm": { type: 'Edm.Boolean' },
        "address1_utcoffset": { type: 'Edm.Int32' },
        "address3_line3": { type: 'Edm.String' },
        "address2_utcoffset": { type: 'Edm.Int32' },
        "suffix": { type: 'Edm.String' },
        "websiteurl": { type: 'Edm.String' },
        "managername": { type: 'Edm.String' },
        "assistantname": { type: 'Edm.String' },
        "address1_latitude": { type: 'Edm.Double' },
        "numberofchildren": { type: 'Edm.Int32' },
        "yomimiddlename": { type: 'Edm.String' },
        "entityimage": { type: 'Edm.Binary' },
        "creditonhold": { type: 'Edm.Boolean' },
        "employeeid": { type: 'Edm.String' },
        "telephone2": { type: 'Edm.String' },
        "address3_freighttermscode": { type: 'Edm.Int32' },
        "jobtitle": { type: 'Edm.String' },
        "fax": { type: 'Edm.String' },
        "followemail": { type: 'Edm.Boolean' },
        "emailaddress2": { type: 'Edm.String' },
        "annualincome": { type: 'Edm.Decimal' },
        "entityimage_url": { type: 'Edm.String' },
        "address1_stateorprovince": { type: 'Edm.String' },
        "address2_telephone2": { type: 'Edm.String' },
        "customertypecode": { type: 'Edm.Int32' },
        "leadsourcecode": { type: 'Edm.Int32' },
        "address3_city": { type: 'Edm.String' },
        "assistantphone": { type: 'Edm.String' },
        "pager": { type: 'Edm.String' },
        "lastname": { type: 'Edm.String' },
        "aging60": { type: 'Edm.Decimal' },
        "donotpostalmail": { type: 'Edm.Boolean' },
        "address3_fax": { type: 'Edm.String' },
        "creditlimit": { type: 'Edm.Decimal' },
        "aging30": { type: 'Edm.Decimal' },
        "coop_customerid": { type: 'Edm.String' },
        "address1_line3": { type: 'Edm.String' },
        "address1_telephone1": { type: 'Edm.String' },
        "childrensnames": { type: 'Edm.String' },
        "address1_city": { type: 'Edm.String' },
        "lastonholdtime": { type: 'Edm.DateTimeOffset' },
        "telephone1": { type: 'Edm.String' },
        "address3_latitude": { type: 'Edm.Double' },
        "preferredappointmentdaycode": { type: 'Edm.Int32' },
        "address3_longitude": { type: 'Edm.Double' },
        "versionnumber": { type: 'Edm.Int64' },
        "address1_name": { type: 'Edm.String' },
        "yomifullname": { type: 'Edm.String' },
        "address3_primarycontactname": { type: 'Edm.String' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "firstname": { type: 'Edm.String' },
        "address2_telephone3": { type: 'Edm.String' },
        "address2_freighttermscode": { type: 'Edm.Int32' },
        "emailaddress1": { type: 'Edm.String' },
        "aging30_base": { type: 'Edm.Decimal' },
        "address1_postofficebox": { type: 'Edm.String' },
        "telephone3": { type: 'Edm.String' },
        "statuscode": { type: 'Edm.Int32' },
        "preferredcontactmethodcode": { type: 'Edm.Int32' },
        "address3_upszone": { type: 'Edm.String' },
        "business2": { type: 'Edm.String' },
        "address3_telephone3": { type: 'Edm.String' },
        "address2_upszone": { type: 'Edm.String' },
        "lastusedincampaign": { type: 'Edm.DateTimeOffset' },
        "businesscard": { type: 'Edm.String' },
        "address1_upszone": { type: 'Edm.String' },
        "familystatuscode": { type: 'Edm.Int32' },
        "address3_line1": { type: 'Edm.String' },
        "address2_county": { type: 'Edm.String' },
        "address1_county": { type: 'Edm.String' },
        "emailaddress3": { type: 'Edm.String' },
        "address2_stateorprovince": { type: 'Edm.String' },
        "address3_postalcode": { type: 'Edm.String' },
        "address3_name": { type: 'Edm.String' },
        "address1_addressid": { type: 'Edm.Guid' },
        "address2_line1": { type: 'Edm.String' },
        "subscriptionid": { type: 'Edm.Guid' },
        "donotfax": { type: 'Edm.Boolean' },
        "address3_county": { type: 'Edm.String' },
        "nickname": { type: 'Edm.String' },
        "haschildrencode": { type: 'Edm.Int32' },
        "address2_country": { type: 'Edm.String' },
        "ftpsiteurl": { type: 'Edm.String' },
        "timespentbymeonemailandmeetings": { type: 'Edm.String' },
        "address3_utcoffset": { type: 'Edm.Int32' },
        "middlename": { type: 'Edm.String' },
        "address2_longitude": { type: 'Edm.Double' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "address2_city": { type: 'Edm.String' },
        "address2_telephone1": { type: 'Edm.String' },
        "Contact_ActivityPointers": { type: 'navigation', target: 'activitypointer', collection: true },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "Contact_Email_EmailSender": { type: 'navigation', target: 'email', collection: true },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "owningteam": { type: 'navigation', target: 'team', collection: false },
        "preferredsystemuserid": { type: 'navigation', target: 'systemuser', collection: false },
        "owninguser": { type: 'navigation', target: 'systemuser', collection: false },
        "ownerid": { type: 'navigation', target: 'principal', collection: false },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "Contact_Emails": { type: 'navigation', target: 'email', collection: true },
        "contact_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "masterid": { type: 'navigation', target: 'contact', collection: false },
        "contact_master_contact": { type: 'navigation', target: 'contact', collection: true },
        "parentcustomerid_contact": { type: 'navigation', target: 'contact', collection: false },
        "contact_customer_contacts": { type: 'navigation', target: 'contact', collection: true },
        "incident_customer_contacts": { type: 'navigation', target: 'incident', collection: true },
        "contact_as_primary_contact": { type: 'navigation', target: 'incident', collection: true },
        "contact_as_responsible_contact": { type: 'navigation', target: 'incident', collection: true },
      },
    },
    "crmbaseentity": {
      properties: {
      },
    },
    "email": {
      baseType: "activitypointer",
      properties: {
        "attachmentopencount": { type: 'Edm.Int32' },
        "sender": { type: 'Edm.String' },
        "isunsafe": { type: 'Edm.Int32' },
        "replycount": { type: 'Edm.Int32' },
        "opencount": { type: 'Edm.Int32' },
        "reminderactioncardid": { type: 'Edm.Guid' },
        "emailreminderexpirytime": { type: 'Edm.DateTimeOffset' },
        "internetmessageheaders": { type: 'Edm.String' },
        "parentsensitivitylabelid": { type: 'Edm.Guid' },
        "trackingtoken": { type: 'Edm.String' },
        "emailtrackingid": { type: 'Edm.Guid' },
        "purviewrights": { type: 'Edm.String' },
        "torecipients": { type: 'Edm.String' },
        "category": { type: 'Edm.String' },
        "correlatedsubjectchanged": { type: 'Edm.Boolean' },
        "emailremindertext": { type: 'Edm.String' },
        "messageid": { type: 'Edm.String' },
        "attachmentcount": { type: 'Edm.Int32' },
        "submittedby": { type: 'Edm.String' },
        "sensitivitylabelinfo": { type: 'Edm.String' },
        "conversationindex": { type: 'Edm.String' },
        "readreceiptrequested": { type: 'Edm.Boolean' },
        "safedescription": { type: 'Edm.String' },
        "subcategory": { type: 'Edm.String' },
        "isemailreminderset": { type: 'Edm.Boolean' },
        "linksclickedcount": { type: 'Edm.Int32' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "delayedemailsendtime": { type: 'Edm.DateTimeOffset' },
        "directioncode": { type: 'Edm.Boolean' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "correlationmethod": { type: 'Edm.Int32' },
        "isemailfollowed": { type: 'Edm.Boolean' },
        "deliveryreceiptrequested": { type: 'Edm.Boolean' },
        "conversationtrackingid": { type: 'Edm.Guid' },
        "deliveryattempts": { type: 'Edm.Int32' },
        "baseconversationindexhash": { type: 'Edm.Int32' },
        "inreplyto": { type: 'Edm.String' },
        "notifications": { type: 'Edm.Int32' },
        "isduplicatesenderunresolved": { type: 'Edm.Boolean' },
        "emailremindertype": { type: 'Edm.Int32' },
        "emailreminderstatus": { type: 'Edm.Int32' },
        "postponeemailprocessinguntil": { type: 'Edm.DateTimeOffset' },
        "mimetype": { type: 'Edm.String' },
        "lastopenedtime": { type: 'Edm.DateTimeOffset' },
        "followemailuserpreference": { type: 'Edm.Boolean' },
        "reservedforinternaluse": { type: 'Edm.String' },
        "compressed": { type: 'Edm.Boolean' },
        "activityid_activitypointer": { type: 'navigation', target: 'activitypointer', collection: false },
        "email_activity_mime_attachment": { type: 'navigation', target: 'activitymimeattachment', collection: true },
        "emailsender_contact": { type: 'navigation', target: 'contact', collection: false },
        "owninguser_email": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedby_email": { type: 'navigation', target: 'systemuser', collection: false },
        "owningteam_email": { type: 'navigation', target: 'team', collection: false },
        "emailsender_queue": { type: 'navigation', target: 'queue', collection: false },
        "createdonbehalfby_email": { type: 'navigation', target: 'systemuser', collection: false },
        "email_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "modifiedonbehalfby_email": { type: 'navigation', target: 'systemuser', collection: false },
        "createdby_email": { type: 'navigation', target: 'systemuser', collection: false },
        "emailsender_systemuser": { type: 'navigation', target: 'systemuser', collection: false },
        "regardingobjectid_contact_email": { type: 'navigation', target: 'contact', collection: false },
        "Email_QueueItem": { type: 'navigation', target: 'queueitem', collection: true },
        "regardingobjectid_incident_email": { type: 'navigation', target: 'incident', collection: false },
        "parentactivityid": { type: 'navigation', target: 'email', collection: false },
        "email_email_parentactivityid": { type: 'navigation', target: 'email', collection: true },
        "ownerid_email": { type: 'navigation', target: 'principal', collection: false },
        "CorrelatedActivityId_Email": { type: 'navigation', target: 'email', collection: false },
        "email_email_CorrelatedActivityId": { type: 'navigation', target: 'email', collection: true },
        "acceptingentityid": { type: 'navigation', target: 'queue', collection: false },
      },
    },
    "incident": {
      baseType: "crmbaseentity",
      properties: {
        "followupby": { type: 'Edm.DateTimeOffset' },
        "entityimage": { type: 'Edm.Binary' },
        "influencescore": { type: 'Edm.Double' },
        "processid": { type: 'Edm.Guid' },
        "actualserviceunits": { type: 'Edm.Int32' },
        "entityimage_url": { type: 'Edm.String' },
        "billedserviceunits": { type: 'Edm.Int32' },
        "ticketnumber": { type: 'Edm.String' },
        "decremententitlementterm": { type: 'Edm.Boolean' },
        "customercontacted": { type: 'Edm.Boolean' },
        "utcconversiontimezonecode": { type: 'Edm.Int32' },
        "isescalated": { type: 'Edm.Boolean' },
        "nextsla": { type: 'Edm.String' },
        "versionnumber": { type: 'Edm.Int64' },
        "lastonholdtime": { type: 'Edm.DateTimeOffset' },
        "merged": { type: 'Edm.Boolean' },
        "coop_resolvedon": { type: 'Edm.DateTimeOffset' },
        "servicestage": { type: 'Edm.Int32' },
        "numberofchildincidents": { type: 'Edm.Int32' },
        "stageid": { type: 'Edm.Guid' },
        "lastinteraction": { type: 'Edm.String' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "checkemail": { type: 'Edm.Boolean' },
        "productserialnumber": { type: 'Edm.String' },
        "firstresponseslastatus": { type: 'Edm.Int32' },
        "statecode": { type: 'Edm.Int32' },
        "emailaddress": { type: 'Edm.String' },
        "onholdtime": { type: 'Edm.Int32' },
        "resolveby": { type: 'Edm.DateTimeOffset' },
        "routecase": { type: 'Edm.Boolean' },
        "isdecrementing": { type: 'Edm.Boolean' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "activitiescomplete": { type: 'Edm.Boolean' },
        "messagetypecode": { type: 'Edm.Int32' },
        "title": { type: 'Edm.String' },
        "description": { type: 'Edm.String' },
        "caseorigincode": { type: 'Edm.Int32' },
        "contractservicelevelcode": { type: 'Edm.Int32' },
        "entityimageid": { type: 'Edm.Guid' },
        "severitycode": { type: 'Edm.Int32' },
        "incidentid": { type: 'Edm.Guid' },
        "traversedpath": { type: 'Edm.String' },
        "customersatisfactioncode": { type: 'Edm.Int32' },
        "entityimage_timestamp": { type: 'Edm.Int64' },
        "followuptaskcreated": { type: 'Edm.Boolean' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "firstresponsesent": { type: 'Edm.Boolean' },
        "prioritycode": { type: 'Edm.Int32' },
        "casetypecode": { type: 'Edm.Int32' },
        "incidentstagecode": { type: 'Edm.Int32' },
        "statuscode": { type: 'Edm.Int32' },
        "timezoneruleversionnumber": { type: 'Edm.Int32' },
        "exchangerate": { type: 'Edm.Decimal' },
        "responseby": { type: 'Edm.DateTimeOffset' },
        "deactivatedon": { type: 'Edm.DateTimeOffset' },
        "escalatedon": { type: 'Edm.DateTimeOffset' },
        "resolvebyslastatus": { type: 'Edm.Int32' },
        "caseage": { type: 'Edm.String' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "blockedprofile": { type: 'Edm.Boolean' },
        "sentimentvalue": { type: 'Edm.Double' },
        "Incident_Emails": { type: 'navigation', target: 'email', collection: true },
        "masterid": { type: 'navigation', target: 'incident', collection: false },
        "incident_master_incident": { type: 'navigation', target: 'incident', collection: true },
        "parentcaseid": { type: 'navigation', target: 'incident', collection: false },
        "incident_parent_incident": { type: 'navigation', target: 'incident', collection: true },
        "existingcase": { type: 'navigation', target: 'incident', collection: false },
        "incident_existingcase": { type: 'navigation', target: 'incident', collection: true },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "owningteam": { type: 'navigation', target: 'team', collection: false },
        "Incident_QueueItem": { type: 'navigation', target: 'queueitem', collection: true },
        "customerid_contact": { type: 'navigation', target: 'contact', collection: false },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "owninguser": { type: 'navigation', target: 'systemuser', collection: false },
        "primarycontactid": { type: 'navigation', target: 'contact', collection: false },
        "responsiblecontactid": { type: 'navigation', target: 'contact', collection: false },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "incident_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "Incident_IncidentResolutions": { type: 'navigation', target: 'incidentresolution', collection: true },
        "Incident_ActivityPointers": { type: 'navigation', target: 'activitypointer', collection: true },
        "ownerid": { type: 'navigation', target: 'principal', collection: false },
      },
    },
    "incidentresolution": {
      baseType: "activitypointer",
      properties: {
        "subcategory": { type: 'Edm.String' },
        "totaltimespent": { type: 'Edm.Int32' },
        "resolutiontypecode": { type: 'Edm.Int32' },
        "category": { type: 'Edm.String' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "timespent": { type: 'Edm.Int32' },
        "ownerid_incidentresolution": { type: 'navigation', target: 'principal', collection: false },
        "activityid_activitypointer": { type: 'navigation', target: 'activitypointer', collection: false },
        "incidentid": { type: 'navigation', target: 'incident', collection: false },
        "incidentresolution_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "owninguser_incidentresolution": { type: 'navigation', target: 'systemuser', collection: false },
        "owningteam_incidentresolution": { type: 'navigation', target: 'team', collection: false },
        "createdonbehalfby_incidentresolution": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedonbehalfby_incidentresolution": { type: 'navigation', target: 'systemuser', collection: false },
        "createdby_incidentresolution": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedby_incidentresolution": { type: 'navigation', target: 'systemuser', collection: false },
      },
    },
    "principal": {
      baseType: "crmbaseentity",
      properties: {
        "ownerid": { type: 'Edm.Guid' },
        "owner_activitypointers": { type: 'navigation', target: 'activitypointer', collection: true },
        "owner_queues": { type: 'navigation', target: 'queue', collection: true },
        "owner_contacts": { type: 'navigation', target: 'contact', collection: true },
        "incidentresolution_owner_ownerid": { type: 'navigation', target: 'incidentresolution', collection: true },
        "owner_emails": { type: 'navigation', target: 'email', collection: true },
        "owner_incidents": { type: 'navigation', target: 'incident', collection: true },
      },
    },
    "queue": {
      baseType: "crmbaseentity",
      properties: {
        "isemailaddressapprovedbyo365admin": { type: 'Edm.Boolean' },
        "queuetypecode": { type: 'Edm.Int32' },
        "queueviewtype": { type: 'Edm.Int32' },
        "incomingemailfilteringmethod": { type: 'Edm.Int32' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "entityimage_url": { type: 'Edm.String' },
        "emailaddress": { type: 'Edm.String' },
        "statecode": { type: 'Edm.Int32' },
        "ignoreunsolicitedemail": { type: 'Edm.Boolean' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "queueid": { type: 'Edm.Guid' },
        "entityimage": { type: 'Edm.Binary' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "name": { type: 'Edm.String' },
        "versionnumber": { type: 'Edm.Int64' },
        "exchangerate": { type: 'Edm.Decimal' },
        "entityimageid": { type: 'Edm.Guid' },
        "incomingemaildeliverymethod": { type: 'Edm.Int32' },
        "emailrouteraccessapproval": { type: 'Edm.Int32' },
        "numberofmembers": { type: 'Edm.Int32' },
        "description": { type: 'Edm.String' },
        "entityimage_timestamp": { type: 'Edm.Int64' },
        "outgoingemaildeliverymethod": { type: 'Edm.Int32' },
        "statuscode": { type: 'Edm.Int32' },
        "numberofitems": { type: 'Edm.Int32' },
        "queue_team": { type: 'navigation', target: 'team', collection: true },
        "queue_entries": { type: 'navigation', target: 'queueitem', collection: true },
        "queue_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "ownerid": { type: 'navigation', target: 'principal', collection: false },
        "primaryuserid": { type: 'navigation', target: 'systemuser', collection: false },
        "Queue_Email_EmailSender": { type: 'navigation', target: 'email', collection: true },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "queuemembership_association": { type: 'navigation', target: 'systemuser', collection: true },
        "queue_system_user": { type: 'navigation', target: 'systemuser', collection: true },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "email_acceptingentity_queue": { type: 'navigation', target: 'email', collection: true },
      },
    },
    "queueitem": {
      baseType: "crmbaseentity",
      properties: {
        "statuscode": { type: 'Edm.Int32' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "title": { type: 'Edm.String' },
        "exchangerate": { type: 'Edm.Decimal' },
        "utcconversiontimezonecode": { type: 'Edm.Int32' },
        "statecode": { type: 'Edm.Int32' },
        "enteredon": { type: 'Edm.DateTimeOffset' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "versionnumber": { type: 'Edm.Int64' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "queueitemid": { type: 'Edm.Guid' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "workeridmodifiedon": { type: 'Edm.DateTimeOffset' },
        "timezoneruleversionnumber": { type: 'Edm.Int32' },
        "objecttypecode": { type: 'Edm.Int32' },
        "inheritedparentclustermode": { type: 'Edm.Int32' },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "workerid_systemuser": { type: 'navigation', target: 'systemuser', collection: false },
        "objectid_activitypointer": { type: 'navigation', target: 'activitypointer', collection: false },
        "queueid": { type: 'navigation', target: 'queue', collection: false },
        "workerid_team": { type: 'navigation', target: 'team', collection: false },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "objectid_email": { type: 'navigation', target: 'email', collection: false },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "objectid_incident": { type: 'navigation', target: 'incident', collection: false },
      },
    },
    "systemuser": {
      baseType: "principal",
      properties: {
        "defaultfilterspopulated": { type: 'Edm.Boolean' },
        "address2_county": { type: 'Edm.String' },
        "domainname": { type: 'Edm.String' },
        "entityimage_timestamp": { type: 'Edm.Int64' },
        "address2_telephone3": { type: 'Edm.String' },
        "address1_latitude": { type: 'Edm.Double' },
        "address2_telephone1": { type: 'Edm.String' },
        "address2_addressid": { type: 'Edm.Guid' },
        "address2_fax": { type: 'Edm.String' },
        "middlename": { type: 'Edm.String' },
        "isallowedbyipfirewall": { type: 'Edm.Boolean' },
        "nickname": { type: 'Edm.String' },
        "address2_stateorprovince": { type: 'Edm.String' },
        "deletedstate": { type: 'Edm.Int32' },
        "address2_longitude": { type: 'Edm.Double' },
        "mobilealertemail": { type: 'Edm.String' },
        "sharepointemailaddress": { type: 'Edm.String' },
        "applicationiduri": { type: 'Edm.String' },
        "applicationid": { type: 'Edm.Guid' },
        "address2_shippingmethodcode": { type: 'Edm.Int32' },
        "address1_name": { type: 'Edm.String' },
        "azureactivedirectoryobjectid": { type: 'Edm.Guid' },
        "defaultodbfoldername": { type: 'Edm.String' },
        "yammeremailaddress": { type: 'Edm.String' },
        "accessmode": { type: 'Edm.Int32' },
        "processid": { type: 'Edm.Guid' },
        "address1_postofficebox": { type: 'Edm.String' },
        "address2_postofficebox": { type: 'Edm.String' },
        "address2_addresstypecode": { type: 'Edm.Int32' },
        "yomilastname": { type: 'Edm.String' },
        "title": { type: 'Edm.String' },
        "disabledreason": { type: 'Edm.String' },
        "systemuserid": { type: 'Edm.Guid' },
        "passportlo": { type: 'Edm.Int32' },
        "address2_line1": { type: 'Edm.String' },
        "organizationid": { type: 'Edm.Guid' },
        "timezoneruleversionnumber": { type: 'Edm.Int32' },
        "internalemailaddress": { type: 'Edm.String' },
        "address2_postalcode": { type: 'Edm.String' },
        "incomingemaildeliverymethod": { type: 'Edm.Int32' },
        "address1_stateorprovince": { type: 'Edm.String' },
        "personalemailaddress": { type: 'Edm.String' },
        "fullname": { type: 'Edm.String' },
        "jobtitle": { type: 'Edm.String' },
        "outgoingemaildeliverymethod": { type: 'Edm.Int32' },
        "isintegrationuser": { type: 'Edm.Boolean' },
        "address1_addresstypecode": { type: 'Edm.Int32' },
        "isdisabled": { type: 'Edm.Boolean' },
        "address2_latitude": { type: 'Edm.Double' },
        "address2_name": { type: 'Edm.String' },
        "address1_country": { type: 'Edm.String' },
        "userlicensetype": { type: 'Edm.Int32' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "address2_country": { type: 'Edm.String' },
        "entityimageid": { type: 'Edm.Guid' },
        "address1_shippingmethodcode": { type: 'Edm.Int32' },
        "address2_city": { type: 'Edm.String' },
        "address1_city": { type: 'Edm.String' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "caltype": { type: 'Edm.Int32' },
        "preferredphonecode": { type: 'Edm.Int32' },
        "address1_line3": { type: 'Edm.String' },
        "preferredaddresscode": { type: 'Edm.Int32' },
        "identityid": { type: 'Edm.Int32' },
        "setupuser": { type: 'Edm.Boolean' },
        "stageid": { type: 'Edm.Guid' },
        "governmentid": { type: 'Edm.String' },
        "mobilephone": { type: 'Edm.String' },
        "firstname": { type: 'Edm.String' },
        "isemailaddressapprovedbyo365admin": { type: 'Edm.Boolean' },
        "photourl": { type: 'Edm.String' },
        "address1_telephone2": { type: 'Edm.String' },
        "address1_longitude": { type: 'Edm.Double' },
        "address2_composite": { type: 'Edm.String' },
        "address1_county": { type: 'Edm.String' },
        "systemmanagedusertype": { type: 'Edm.Int32' },
        "emailrouteraccessapproval": { type: 'Edm.Int32' },
        "skills": { type: 'Edm.String' },
        "islicensed": { type: 'Edm.Boolean' },
        "issyncwithdirectory": { type: 'Edm.Boolean' },
        "address1_postalcode": { type: 'Edm.String' },
        "lastname": { type: 'Edm.String' },
        "address2_upszone": { type: 'Edm.String' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "traversedpath": { type: 'Edm.String' },
        "windowsliveid": { type: 'Edm.String' },
        "versionnumber": { type: 'Edm.Int64' },
        "yomifirstname": { type: 'Edm.String' },
        "passporthi": { type: 'Edm.Int32' },
        "exchangerate": { type: 'Edm.Decimal' },
        "displayinserviceviews": { type: 'Edm.Boolean' },
        "preferredemailcode": { type: 'Edm.Int32' },
        "employeeid": { type: 'Edm.String' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "invitestatuscode": { type: 'Edm.Int32' },
        "address1_line2": { type: 'Edm.String' },
        "address2_utcoffset": { type: 'Edm.Int32' },
        "utcconversiontimezonecode": { type: 'Edm.Int32' },
        "address1_fax": { type: 'Edm.String' },
        "address1_composite": { type: 'Edm.String' },
        "yomifullname": { type: 'Edm.String' },
        "address2_line3": { type: 'Edm.String' },
        "entityimage_url": { type: 'Edm.String' },
        "address1_telephone3": { type: 'Edm.String' },
        "address1_telephone1": { type: 'Edm.String' },
        "yomimiddlename": { type: 'Edm.String' },
        "azuredeletedon": { type: 'Edm.DateTimeOffset' },
        "address2_line2": { type: 'Edm.String' },
        "address1_addressid": { type: 'Edm.Guid' },
        "salutation": { type: 'Edm.String' },
        "userpuid": { type: 'Edm.String' },
        "address1_line1": { type: 'Edm.String' },
        "address1_upszone": { type: 'Edm.String' },
        "entityimage": { type: 'Edm.Binary' },
        "address1_utcoffset": { type: 'Edm.Int32' },
        "yammeruserid": { type: 'Edm.String' },
        "homephone": { type: 'Edm.String' },
        "azurestate": { type: 'Edm.Int32' },
        "address2_telephone2": { type: 'Edm.String' },
        "teammembership_association": { type: 'navigation', target: 'team', collection: true },
        "lk_activitypointer_createdby": { type: 'navigation', target: 'activitypointer', collection: true },
        "lk_queueitembase_createdby": { type: 'navigation', target: 'queueitem', collection: true },
        "lk_queueitembase_modifiedby": { type: 'navigation', target: 'queueitem', collection: true },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "lk_systemuser_modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: true },
        "lk_queueitembase_workerid": { type: 'navigation', target: 'queueitem', collection: true },
        "lk_contact_createdonbehalfby": { type: 'navigation', target: 'contact', collection: true },
        "lk_team_modifiedonbehalfby": { type: 'navigation', target: 'team', collection: true },
        "user_activity": { type: 'navigation', target: 'activitypointer', collection: true },
        "system_user_activity_parties": { type: 'navigation', target: 'activityparty', collection: true },
        "lk_contact_modifiedonbehalfby": { type: 'navigation', target: 'contact', collection: true },
        "user_email": { type: 'navigation', target: 'email', collection: true },
        "lk_contactbase_createdby": { type: 'navigation', target: 'contact', collection: true },
        "lk_email_modifiedby": { type: 'navigation', target: 'email', collection: true },
        "queue_primary_user": { type: 'navigation', target: 'queue', collection: true },
        "lk_activitypointer_modifiedonbehalfby": { type: 'navigation', target: 'activitypointer', collection: true },
        "lk_activitypointer_createdonbehalfby": { type: 'navigation', target: 'activitypointer', collection: true },
        "lk_activitypointer_modifiedby": { type: 'navigation', target: 'activitypointer', collection: true },
        "lk_queuebase_createdby": { type: 'navigation', target: 'queue', collection: true },
        "lk_queueitem_modifiedonbehalfby": { type: 'navigation', target: 'queueitem', collection: true },
        "lk_email_createdonbehalfby": { type: 'navigation', target: 'email', collection: true },
        "lk_queue_modifiedonbehalfby": { type: 'navigation', target: 'queue', collection: true },
        "system_user_contacts": { type: 'navigation', target: 'contact', collection: true },
        "lk_teambase_modifiedby": { type: 'navigation', target: 'team', collection: true },
        "queuemembership_association": { type: 'navigation', target: 'queue', collection: true },
        "contact_owning_user": { type: 'navigation', target: 'contact', collection: true },
        "lk_teambase_createdby": { type: 'navigation', target: 'team', collection: true },
        "lk_email_modifiedonbehalfby": { type: 'navigation', target: 'email', collection: true },
        "queueid": { type: 'navigation', target: 'queue', collection: false },
        "lk_email_createdby": { type: 'navigation', target: 'email', collection: true },
        "lk_queue_createdonbehalfby": { type: 'navigation', target: 'queue', collection: true },
        "lk_queuebase_modifiedby": { type: 'navigation', target: 'queue', collection: true },
        "SystemUser_Email_EmailSender": { type: 'navigation', target: 'email', collection: true },
        "lk_team_createdonbehalfby": { type: 'navigation', target: 'team', collection: true },
        "lk_contactbase_modifiedby": { type: 'navigation', target: 'contact', collection: true },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "lk_systemuser_createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: true },
        "lk_teambase_administratorid": { type: 'navigation', target: 'team', collection: true },
        "lk_queueitem_createdonbehalfby": { type: 'navigation', target: 'queueitem', collection: true },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "lk_systemuserbase_createdby": { type: 'navigation', target: 'systemuser', collection: true },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "lk_systemuserbase_modifiedby": { type: 'navigation', target: 'systemuser', collection: true },
        "parentsystemuserid": { type: 'navigation', target: 'systemuser', collection: false },
        "user_parent_user": { type: 'navigation', target: 'systemuser', collection: true },
        "lk_incidentbase_modifiedonbehalfby": { type: 'navigation', target: 'incident', collection: true },
        "lk_incidentbase_createdby": { type: 'navigation', target: 'incident', collection: true },
        "system_user_incidents": { type: 'navigation', target: 'incident', collection: true },
        "lk_incidentbase_createdonbehalfby": { type: 'navigation', target: 'incident', collection: true },
        "lk_incidentbase_modifiedby": { type: 'navigation', target: 'incident', collection: true },
        "user_incidentresolution": { type: 'navigation', target: 'incidentresolution', collection: true },
        "lk_incidentresolution_createdonbehalfby": { type: 'navigation', target: 'incidentresolution', collection: true },
        "lk_incidentresolution_modifiedonbehalfby": { type: 'navigation', target: 'incidentresolution', collection: true },
        "lk_incidentresolution_createdby": { type: 'navigation', target: 'incidentresolution', collection: true },
        "lk_incidentresolution_modifiedby": { type: 'navigation', target: 'incidentresolution', collection: true },
      },
    },
    "team": {
      baseType: "principal",
      properties: {
        "membershiptype": { type: 'Edm.Int32' },
        "isdefault": { type: 'Edm.Boolean' },
        "traversedpath": { type: 'Edm.String' },
        "yominame": { type: 'Edm.String' },
        "exchangerate": { type: 'Edm.Decimal' },
        "issastokenset": { type: 'Edm.Boolean' },
        "organizationid": { type: 'Edm.Guid' },
        "systemmanaged": { type: 'Edm.Boolean' },
        "name": { type: 'Edm.String' },
        "importsequencenumber": { type: 'Edm.Int32' },
        "teamtype": { type: 'Edm.Int32' },
        "versionnumber": { type: 'Edm.Int64' },
        "description": { type: 'Edm.String' },
        "emailaddress": { type: 'Edm.String' },
        "processid": { type: 'Edm.Guid' },
        "teamid": { type: 'Edm.Guid' },
        "overriddencreatedon": { type: 'Edm.DateTimeOffset' },
        "sharelinkqualifier": { type: 'Edm.String' },
        "modifiedon": { type: 'Edm.DateTimeOffset' },
        "stageid": { type: 'Edm.Guid' },
        "createdon": { type: 'Edm.DateTimeOffset' },
        "azureactivedirectoryobjectid": { type: 'Edm.Guid' },
        "teammembership_association": { type: 'navigation', target: 'systemuser', collection: true },
        "queueid": { type: 'navigation', target: 'queue', collection: false },
        "modifiedonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "team_queueitembase_workerid": { type: 'navigation', target: 'queueitem', collection: true },
        "team_email": { type: 'navigation', target: 'email', collection: true },
        "team_contacts": { type: 'navigation', target: 'contact', collection: true },
        "modifiedby": { type: 'navigation', target: 'systemuser', collection: false },
        "createdby": { type: 'navigation', target: 'systemuser', collection: false },
        "team_activity": { type: 'navigation', target: 'activitypointer', collection: true },
        "createdonbehalfby": { type: 'navigation', target: 'systemuser', collection: false },
        "administratorid": { type: 'navigation', target: 'systemuser', collection: false },
        "team_incidents": { type: 'navigation', target: 'incident', collection: true },
        "team_incidentresolution": { type: 'navigation', target: 'incidentresolution', collection: true },
      },
    },
  },
  entitysets: {
    "activitymimeattachments": {
      entitytype: "activitymimeattachment",
    },
    "activityparties": {
      entitytype: "activityparty",
    },
    "contacts": {
      entitytype: "contact",
    },
    "emails": {
      entitytype: "email",
    },
    "incidentresolutions": {
      entitytype: "incidentresolution",
    },
    "incidents": {
      entitytype: "incident",
    },
    "queueitems": {
      entitytype: "queueitem",
    },
    "queues": {
      entitytype: "queue",
    },
    "systemusers": {
      entitytype: "systemuser",
    },
    "teams": {
      entitytype: "team",
    },
  },
  actions: {
      "AddPrincipalToQueue": {
        type: 'bound',
        collection: false,
        target: 'queue',
        parameters: {
          "Principal": { type: 'navigation', target: 'crmbaseentity' },
        },
      },
      "AddToQueue": {
        type: 'bound',
        collection: false,
        target: 'queue',
        parameters: {
          "Target": { type: 'navigation', target: 'crmbaseentity' },
          "SourceQueue": { type: 'navigation', target: 'queue' },
          "QueueItemProperties": { type: 'navigation', target: 'queueitem' },
        },
        returnType: { type: 'complex', target: 'AddToQueueResponse' },
      },
      "SendEmail": {
        type: 'bound',
        collection: false,
        target: 'email',
        parameters: {
          "IssueSend": { type: 'Edm.Boolean' },
          "TrackingToken": { type: 'Edm.String' },
        },
        returnType: { type: 'complex', target: 'SendEmailResponse' },
      },
      "CloseIncident": {
        type: 'unbound',
        parameters: {
          "IncidentResolution": { type: 'navigation', target: 'incidentresolution' },
          "Status": { type: 'Edm.Int32' },
        },
      },
  },
  functions: {
      "WhoAmI": {
        type: 'unbound',
        parameters: {
        },
        returnType: { type: 'complex', target: 'WhoAmIResponse' },
      },
  },
  actionImports: {
    "CloseIncident": {
      action: "CloseIncident",
    },
  },
  functionImports: {
    "WhoAmI": {
      function: "WhoAmI",
    },
  },
});
