import { property, schema } from "./schema";

export const microsoft_dynamics_crm_schema = schema({
  namespace: "Microsoft.Dynamics.CRM",
  complexTypes: {
    "crmbaseentity": {
      properties: {
      },
    },
    "SendEmailResponse": {
      properties: {
        "Subject": property("string"),
      },
    },
    "CalculateTotalTimeIncidentResponse": {
      properties: {
        "TotalTime": property("number"),
      },
    },
    "RetrievePrincipalAccessResponse": {
      properties: {
        "AccessRights": property("any" as any, {  }), // AccessRights
      },
    },
    "RetrievePrincipalAccessInfoResponse": {
      properties: {
        "AccessInfo": property("string"),
      },
    },
    "RetrievePrincipalAttributePrivilegesResponse": {
      properties: {
        "AttributePrivileges": property("any" as any, { collection: true }), // AttributePrivilege
      },
    },
    "RetrievePrincipalSyncAttributeMappingsResponse": {
      properties: {
        "AttributeMappings": property("any" as any, { collection: true }), // AttributeMapping
      },
    },
    "RetrieveTeamPrivilegesResponse": {
      properties: {
        "RolePrivileges": property("any" as any, { collection: true }), // RolePrivilege
      },
    },
    "RetrieveTimelineWallRecordsResponse": {
      properties: {
        "TimelineWallRecords": property("string"),
      },
    },
    "AttributePrivilege": {
      properties: {
        "AttributeId": property("guid"),
        "CanCreate": property("number"),
        "CanRead": property("number"),
        "CanUpdate": property("number"),
        "CanReadUnMasked": property("number"),
      },
    },
    "AttributeMapping": {
      properties: {
        "AttributeMappingId": property("guid"),
        "MappingName": property("string"),
        "AttributeCrmName": property("string"),
        "AttributeExchangeName": property("string"),
        "SyncDirection": property("number"),
        "DefaultSyncDirection": property("number"),
        "AllowedSyncDirection": property("number"),
        "IsComputed": property("boolean"),
        "EntityTypeCode": property("number"),
        "ComputedProperties": property("string", { collection: true }),
        "AttributeCrmDisplayName": property("string"),
        "AttributeExchangeDisplayName": property("string"),
      },
    },
    "RolePrivilege": {
      properties: {
        "Depth": property("any" as any, {  }), // PrivilegeDepth
        "PrivilegeId": property("guid"),
        "BusinessUnitId": property("guid"),
        "PrivilegeName": property("string"),
        "RecordFilterId": property("guid"),
        "RecordFilterUniqueName": property("string"),
      },
    },
  },
  entitysets: {
    "activitymimeattachments": {
      properties: {
        "versionnumber": property("number"),
        "componentstate": property("number"),
        "filename": property("string"),
        "overwritetime": property("datetimeoffset"),
        "subject": property("string"),
        "filesize": property("number"),
        "ismanaged": property("boolean"),
        "activitymimeattachmentid": property("key", { readonly: true }),
        "attachmentcontentid": property("string"),
        "objecttypecode": property("string"),
        "activitymimeattachmentidunique": property("guid"),
        "mimetype": property("string"),
        "solutionid": property("guid"),
        "activitysubject": property("string"),
        "attachmentnumber": property("number"),
        "anonymouslink": property("string"),
        "isfollowed": property("boolean"),
        "body": property("string"),
        "body_binary": property("binary"),
      },
      navigations: {
        "objectid_email": { target: "emails", collection: false },
        "objectid_activitypointer": { target: "activitypointers", collection: false },
      },
      actions: {
      },
      functions: {
      },
    },
    "activityparties": {
      properties: {
        "donotfax": property("boolean"),
        "scheduledend": property("datetimeoffset"),
        "effort": property("number"),
        "addressusedemailcolumnnumber": property("number"),
        "donotpostalmail": property("boolean"),
        "unresolvedpartyname": property("string"),
        "ispartydeleted": property("boolean"),
        "externalidtype": property("string"),
        "activitypartyid": property("key", { readonly: true }),
        "scheduledstart": property("datetimeoffset"),
        "instancetypecode": property("number"),
        "versionnumber": property("number"),
        "donotemail": property("boolean"),
        "exchangeentryid": property("string"),
        "addressused": property("string"),
        "externalid": property("string"),
        "donotphone": property("boolean"),
        "participationtypemask": property("number"),
      },
      navigations: {
        "activityid_email": { target: "emails", collection: false },
        "activityid_activitypointer": { target: "activitypointers", collection: false },
        "partyid_contact": { target: "contacts", collection: false },
        "partyid_incident": { target: "incidents", collection: false },
        "activityid_incidentresolution": { target: "incidentresolutions", collection: false },
      },
      actions: {
      },
      functions: {
      },
    },
    "activitypointers": {
      properties: {
        "ismapiprivate": property("boolean"),
        "onholdtime": property("number"),
        "seriesid": property("guid"),
        "leftvoicemail": property("boolean"),
        "description": property("string"),
        "deliverylastattemptedon": property("datetimeoffset"),
        "exchangerate": property("number"),
        "isbilled": property("boolean"),
        "instancetypecode": property("number"),
        "traversedpath": property("string"),
        "descriptionblobid": property("binary"),
        "scheduledstart": property("datetimeoffset"),
        "activityadditionalparams": property("string"),
        "subject": property("string"),
        "scheduleddurationminutes": property("number"),
        "community": property("number"),
        "versionnumber": property("number"),
        "actualdurationminutes": property("number"),
        "lastonholdtime": property("datetimeoffset"),
        "isworkflowcreated": property("boolean"),
        "scheduledend": property("datetimeoffset"),
        "isregularactivity": property("boolean"),
        "exchangeweblink": property("string"),
        "postponeactivityprocessinguntil": property("datetimeoffset"),
        "formattedscheduledend": property("datetimeoffset"),
        "exchangeitemid": property("string"),
        "processid": property("guid"),
        "sortdate": property("datetimeoffset"),
        "stageid": property("guid"),
        "activityid": property("key", { readonly: true }),
        "modifiedon": property("datetimeoffset"),
        "createdon": property("datetimeoffset"),
        "formattedscheduledstart": property("datetimeoffset"),
        "descriptionblobid_name": property("string"),
        "senton": property("datetimeoffset"),
        "statuscode": property("number"),
        "statecode": property("number"),
        "actualstart": property("datetimeoffset"),
        "prioritycode": property("number"),
        "deliveryprioritycode": property("number"),
        "actualend": property("datetimeoffset"),
        "timezoneruleversionnumber": property("number"),
        "utcconversiontimezonecode": property("number"),
        "activitytypecode": property("string"),
      },
      navigations: {
        "regardingobjectid_contact": { target: "contacts", collection: false },
        "activity_pointer_email": { target: "emails", collection: true },
        "activity_pointer_activity_mime_attachment": { target: "activitymimeattachments", collection: true },
        "owningteam": { target: "teams", collection: false },
        "activitypointer_activity_parties": { target: "activityparties", collection: true },
        "activity_pointer_incident_resolution": { target: "incidentresolutions", collection: true },
        "regardingobjectid_incident": { target: "incidents", collection: false },
      },
      actions: {
      },
      functions: {
        "RetrieveTimelineWallRecords": {
          scope: "collection",
          parameters: {
        "FetchXml": property("string", { nullable: false }),
        "Target": property("any" as any, {  }), // crmbaseentity
        "RollupType": property("number"),
          },
          returnType: { target: "RetrieveTimelineWallRecordsResponse", collection: false },
        },
      },
    },
    "contacts": {
      properties: {
        "address2_freighttermscode": property("number"),
        "educationcode": property("number"),
        "address3_city": property("string"),
        "lms_currentpointbalance": property("number"),
        "aging90": property("number"),
        "coop_blocked": property("boolean"),
        "address2_stateorprovince": property("string"),
        "coop_costplace": property("number"),
        "managerphone": property("string"),
        "accountrolecode": property("number"),
        "childrensnames": property("string"),
        "shippingmethodcode": property("number"),
        "address1_addresstypecode": property("number"),
        "address2_line2": property("string"),
        "utcconversiontimezonecode": property("number"),
        "annualincome_base": property("number"),
        "mspp_userpreferredlcid": property("number"),
        "address1_composite": property("string"),
        "address2_postofficebox": property("string"),
        "address3_telephone1": property("string"),
        "onholdtime": property("number"),
        "telephone3": property("string"),
        "creditlimit_base": property("number"),
        "coop_customerconcern": property("number"),
        "entityimageid": property("guid"),
        "coop_paymentcardscore": property("number"),
        "statecode": property("number"),
        "address2_postalcode": property("string"),
        "entityimage_timestamp": property("number"),
        "coop_title": property("string"),
        "lms_amountspentcurrentmonth": property("number"),
        "lms_purchase_todate": property("datetimeoffset"),
        "address3_shippingmethodcode": property("number"),
        "coop_reportdate": property("date"),
        "coop_connectedtohrsupport": property("boolean"),
        "stageid": property("guid"),
        "address2_name": property("string"),
        "mobilephone": property("string"),
        "address1_line1": property("string"),
        "aging60_base": property("number"),
        "coop_kimcustomerid": property("string"),
        "timezoneruleversionnumber": property("number"),
        "businesscardattributes": property("string"),
        "address1_fax": property("string"),
        "yomilastname": property("string"),
        "address1_telephone3": property("string"),
        "address1_country": property("string"),
        "coop_custommodifiedon": property("date"),
        "coop_date": property("date"),
        "gendercode": property("number"),
        "merged": property("boolean"),
        "anniversary": property("date"),
        "lms_depersonalise": property("boolean"),
        "address1_line2": property("string"),
        "address2_addressid": property("guid"),
        "address3_stateorprovince": property("string"),
        "birthdate": property("date"),
        "address1_shippingmethodcode": property("number"),
        "address2_shippingmethodcode": property("number"),
        "salutation": property("string"),
        "coop_primarycontact": property("boolean"),
        "governmentid": property("string"),
        "home2": property("string"),
        "coop_membercardnr": property("string"),
        "coop_mepupsert": property("boolean"),
        "coop_unitname": property("number"),
        "coop_householdid": property("string"),
        "coop_suppliercontact": property("boolean"),
        "address2_composite": property("string"),
        "address1_addressid": property("guid"),
        "coop_reportstatusop": property("number"),
        "coop_role": property("number"),
        "coop_isexpertcontact": property("boolean"),
        "callback": property("string"),
        "fax": property("string"),
        "modifiedon": property("datetimeoffset"),
        "fullname": property("string"),
        "address2_latitude": property("number"),
        "lms_earnedpoints_expiringdate": property("datetimeoffset"),
        "preferredappointmenttimecode": property("number"),
        "lms_amountspentcurrentmonth_base": property("number"),
        "address1_primarycontactname": property("string"),
        "isbackofficecustomer": property("boolean"),
        "description": property("string"),
        "donotbulkpostalmail": property("boolean"),
        "paymenttermscode": property("number"),
        "donotphone": property("boolean"),
        "teamsfollowed": property("number"),
        "address3_postofficebox": property("string"),
        "territorycode": property("number"),
        "address3_line2": property("string"),
        "externaluseridentifier": property("string"),
        "coop_personalnumber": property("string"),
        "emailaddress2": property("string"),
        "importsequencenumber": property("number"),
        "yomifirstname": property("string"),
        "address1_postalcode": property("string"),
        "address1_telephone2": property("string"),
        "lms_earnedpoints_type": property("number"),
        "spousesname": property("string"),
        "address3_country": property("string"),
        "address1_longitude": property("number"),
        "participatesinworkflow": property("boolean"),
        "lms_loyalitystatus": property("boolean"),
        "address3_composite": property("string"),
        "coop_handlahemmacustomernumber": property("string"),
        "aging90_base": property("number"),
        "address2_primarycontactname": property("string"),
        "coop_job_title": property("string"),
        "contactid": property("key", { readonly: true }),
        "overriddencreatedon": property("datetimeoffset"),
        "lms_ecmodifiedon": property("datetimeoffset"),
        "coop_flowcontact": property("string"),
        "coop_coopposition": property("number"),
        "address3_addresstypecode": property("number"),
        "address2_line3": property("string"),
        "address1_utcoffset": property("number"),
        "address3_telephone2": property("string"),
        "address3_line3": property("string"),
        "address2_utcoffset": property("number"),
        "coop_transactiondate": property("date"),
        "suffix": property("string"),
        "websiteurl": property("string"),
        "managername": property("string"),
        "assistantname": property("string"),
        "address1_latitude": property("number"),
        "numberofchildren": property("number"),
        "lms_ishouseholdowner": property("boolean"),
        "traversedpath": property("string"),
        "entityimage": property("binary"),
        "creditonhold": property("boolean"),
        "telephone1": property("string"),
        "nickname": property("string"),
        "employeeid": property("string"),
        "telephone2": property("string"),
        "coop_external_customer_id": property("string"),
        "company": property("string"),
        "address3_freighttermscode": property("number"),
        "jobtitle": property("string"),
        "followemail": property("boolean"),
        "coop_attentionreason": property("string"),
        "coop_unit": property("number"),
        "annualincome": property("number"),
        "coop_mobileoption": property("boolean"),
        "entityimage_url": property("string"),
        "coop_emailoption": property("boolean"),
        "lms_earnedpoints_expiringpoints": property("number"),
        "customertypecode": property("number"),
        "marketingonly": property("boolean"),
        "assistantphone": property("string"),
        "pager": property("string"),
        "lastname": property("string"),
        "ftpsiteurl": property("string"),
        "donotpostalmail": property("boolean"),
        "address3_fax": property("string"),
        "creditlimit": property("number"),
        "exchangerate": property("number"),
        "address2_longitude": property("number"),
        "address2_addresstypecode": property("number"),
        "aging30": property("number"),
        "coop_customerid": property("string"),
        "address3_longitude": property("number"),
        "address1_line3": property("string"),
        "address1_telephone1": property("string"),
        "address1_city": property("string"),
        "coop_cat_role": property("string"),
        "address3_latitude": property("number"),
        "preferredappointmentdaycode": property("number"),
        "coop_isdeceased": property("boolean"),
        "versionnumber": property("number"),
        "department": property("string"),
        "address1_name": property("string"),
        "yomifullname": property("string"),
        "address3_addressid": property("guid"),
        "firstname": property("string"),
        "coop_date2": property("datetimeoffset"),
        "lms_earnedpoints_fromdate": property("datetimeoffset"),
        "address3_county": property("string"),
        "customersizecode": property("number"),
        "address2_telephone2": property("string"),
        "emailaddress1": property("string"),
        "business2": property("string"),
        "lms_priorhousholdid": property("string"),
        "aging30_base": property("number"),
        "address1_postofficebox": property("string"),
        "coop_contacttype": property("number"),
        "address2_fax": property("string"),
        "address2_city": property("string"),
        "coop_cbscontact": property("boolean"),
        "address2_telephone3": property("string"),
        "statuscode": property("number"),
        "preferredcontactmethodcode": property("number"),
        "leadsourcecode": property("number"),
        "donotsendmm": property("boolean"),
        "address3_upszone": property("string"),
        "address2_line1": property("string"),
        "address3_telephone3": property("string"),
        "address2_upszone": property("string"),
        "lastusedincampaign": property("datetimeoffset"),
        "subscriptionid": property("guid"),
        "businesscard": property("string"),
        "address1_upszone": property("string"),
        "familystatuscode": property("number"),
        "yomimiddlename": property("string"),
        "address3_line1": property("string"),
        "address2_county": property("string"),
        "address1_county": property("string"),
        "donotbulkemail": property("boolean"),
        "coop_customerstatus": property("boolean"),
        "emailaddress3": property("string"),
        "aging60": property("number"),
        "address1_stateorprovince": property("string"),
        "lms_currentmatrixlevel": property("number"),
        "address3_postalcode": property("string"),
        "coop_orgbelonging": property("string"),
        "address3_name": property("string"),
        "coop_deceaseddate": property("date"),
        "address1_freighttermscode": property("number"),
        "lms_earnedpoints_points": property("number"),
        "address3_primarycontactname": property("string"),
        "donotfax": property("boolean"),
        "lms_purchase_fromdate": property("datetimeoffset"),
        "lastonholdtime": property("datetimeoffset"),
        "coop_mach1householdid": property("string"),
        "haschildrencode": property("number"),
        "coop_function": property("string"),
        "address2_country": property("string"),
        "processid": property("guid"),
        "coop_personnumbertype": property("number"),
        "timespentbymeonemailandmeetings": property("string"),
        "address3_utcoffset": property("number"),
        "lms_earnedpoints_todate": property("datetimeoffset"),
        "middlename": property("string"),
        "coop_deletedate": property("date"),
        "coop_attentioncustomer": property("boolean"),
        "createdon": property("datetimeoffset"),
        "donotemail": property("boolean"),
        "address2_telephone1": property("string"),
      },
      navigations: {
        "Contact_ActivityPointers": { target: "activitypointers", collection: true },
        "Contact_Email_EmailSender": { target: "emails", collection: true },
        "owningteam": { target: "teams", collection: false },
        "Contact_Emails": { target: "emails", collection: true },
        "contact_activity_parties": { target: "activityparties", collection: true },
        "coop_CBSManager": { target: "contacts", collection: false },
        "coop_contact_contact_CBSManager": { target: "contacts", collection: true },
        "coop_manager": { target: "contacts", collection: false },
        "coop_contact_contact": { target: "contacts", collection: true },
        "masterid": { target: "contacts", collection: false },
        "contact_master_contact": { target: "contacts", collection: true },
        "parentcustomerid_contact": { target: "contacts", collection: false },
        "contact_customer_contacts": { target: "contacts", collection: true },
        "coop_contact_incident_Reporter": { target: "incidents", collection: true },
        "incident_customer_contacts": { target: "incidents", collection: true },
        "contact_as_primary_contact": { target: "incidents", collection: true },
        "contact_as_responsible_contact": { target: "incidents", collection: true },
        "coop_contact_incident_webformsender": { target: "incidents", collection: true },
        "coop_contact_incident_Contact": { target: "incidents", collection: true },
      },
      actions: {
      },
      functions: {
      },
    },
    "emails": {
      baseType: "activitypointers",
      properties: {
        "safedescription": property("string"),
        "attachmentopencount": property("number"),
        "coop_deletedate": property("datetimeoffset"),
        "isunsafe": property("number"),
        "replycount": property("number"),
        "opencount": property("number"),
        "reminderactioncardid": property("guid"),
        "emailreminderexpirytime": property("datetimeoffset"),
        "internetmessageheaders": property("string"),
        "parentsensitivitylabelid": property("guid"),
        "coop_storeemailaddress2": property("string"),
        "trackingtoken": property("string"),
        "emailtrackingid": property("guid"),
        "sender": property("string"),
        "torecipients": property("string"),
        "category": property("string"),
        "coop_email2_checkbox": property("boolean"),
        "emailremindertext": property("string"),
        "messageid": property("string"),
        "attachmentcount": property("number"),
        "coop_email1_checkbox": property("boolean"),
        "coop_storeemailaddress1": property("string"),
        "coop_source": property("number"),
        "submittedby": property("string"),
        "sensitivitylabelinfo": property("string"),
        "conversationindex": property("string"),
        "readreceiptrequested": property("boolean"),
        "subcategory": property("string"),
        "notifications": property("number"),
        "isemailreminderset": property("boolean"),
        "correlatedsubjectchanged": property("boolean"),
        "coop_email3_checkbox": property("boolean"),
        "linksclickedcount": property("number"),
        "overriddencreatedon": property("datetimeoffset"),
        "delayedemailsendtime": property("datetimeoffset"),
        "directioncode": property("boolean"),
        "importsequencenumber": property("number"),
        "correlationmethod": property("number"),
        "isemailfollowed": property("boolean"),
        "deliveryreceiptrequested": property("boolean"),
        "conversationtrackingid": property("guid"),
        "deliveryattempts": property("number"),
        "baseconversationindexhash": property("number"),
        "inreplyto": property("string"),
        "isduplicatesenderunresolved": property("boolean"),
        "emailremindertype": property("number"),
        "coop_storeemailaddress3": property("string"),
        "emailreminderstatus": property("number"),
        "postponeemailprocessinguntil": property("datetimeoffset"),
        "mimetype": property("string"),
        "lastopenedtime": property("datetimeoffset"),
        "followemailuserpreference": property("boolean"),
        "reservedforinternaluse": property("string"),
        "compressed": property("boolean"),
      },
      navigations: {
        "activityid_activitypointer": { target: "activitypointers", collection: false },
        "email_activity_mime_attachment": { target: "activitymimeattachments", collection: true },
        "emailsender_contact": { target: "contacts", collection: false },
        "owningteam_email": { target: "teams", collection: false },
        "email_activity_parties": { target: "activityparties", collection: true },
        "regardingobjectid_contact_email": { target: "contacts", collection: false },
        "regardingobjectid_incident_email": { target: "incidents", collection: false },
        "parentactivityid": { target: "emails", collection: false },
        "email_email_parentactivityid": { target: "emails", collection: true },
        "CorrelatedActivityId_Email": { target: "emails", collection: false },
        "email_email_CorrelatedActivityId": { target: "emails", collection: true },
        "coop_CaseforBSPortalEmail_Email": { target: "incidents", collection: false },
      },
      actions: {
        "DeliverImmediatePromoteEmail": {
          scope: "entity",
          parameters: {
        "MessageId": property("string", { nullable: false }),
        "Subject": property("string"),
        "From": property("string", { nullable: false }),
        "To": property("string", { nullable: false }),
        "Cc": property("string", { nullable: false }),
        "Bcc": property("string", { nullable: false }),
        "ReceivedOn": property("datetimeoffset", { nullable: false }),
        "SubmittedBy": property("string", { nullable: false }),
        "Importance": property("string", { nullable: false }),
        "Body": property("string", { nullable: false }),
        "AttachmentIds": property("string", { collection: true }),
        "EWSUrl": property("string"),
        "AttachmentToken": property("string"),
        "ExtraProperties": property("any" as any, {  }), // crmbaseentity
          },
          returnType: { target: "emails", collection: false },
        },
        "DeliverIncomingEmail": {
          scope: "collection",
          parameters: {
        "MessageId": property("string", { nullable: false }),
        "Subject": property("string"),
        "From": property("string", { nullable: false }),
        "To": property("string", { nullable: false }),
        "Cc": property("string", { nullable: false }),
        "Bcc": property("string", { nullable: false }),
        "ReceivedOn": property("datetimeoffset", { nullable: false }),
        "SubmittedBy": property("string", { nullable: false }),
        "Importance": property("string", { nullable: false }),
        "Body": property("string", { nullable: false }),
        "Attachments": { target: "activitymimeattachments", collection: true },
        "ExtraProperties": { target: "emails", collection: false },
        "ValidateBeforeCreate": property("boolean"),
          },
          returnType: { target: "emails", collection: false },
        },
        "DeliverPromoteEmail": {
          scope: "entity",
          parameters: {
        "MessageId": property("string", { nullable: false }),
        "Subject": property("string"),
        "From": property("string", { nullable: false }),
        "To": property("string", { nullable: false }),
        "Cc": property("string", { nullable: false }),
        "Bcc": property("string", { nullable: false }),
        "ReceivedOn": property("datetimeoffset", { nullable: false }),
        "SubmittedBy": property("string", { nullable: false }),
        "Importance": property("string", { nullable: false }),
        "Body": property("string", { nullable: false }),
        "Attachments": { target: "activitymimeattachments", collection: true },
        "ExtraProperties": { target: "emails", collection: false },
          },
          returnType: { target: "emails", collection: false },
        },
        "ProcessInboundEmail": {
          scope: "entity",
          parameters: {
          },
        },
        "SendEmail": {
          scope: "entity",
          parameters: {
        "IssueSend": property("boolean", { nullable: false }),
        "TrackingToken": property("string"),
          },
          returnType: { target: "SendEmailResponse", collection: false },
        },
      },
      functions: {
      },
    },
    "incidentresolutions": {
      baseType: "activitypointers",
      properties: {
        "subcategory": property("string"),
        "totaltimespent": property("number"),
        "resolutiontypecode": property("number"),
        "category": property("string"),
        "importsequencenumber": property("number"),
        "timespent": property("number"),
        "overriddencreatedon": property("datetimeoffset"),
      },
      navigations: {
        "activityid_activitypointer": { target: "activitypointers", collection: false },
        "incidentid": { target: "incidents", collection: false },
        "incidentresolution_activity_parties": { target: "activityparties", collection: true },
        "owningteam_incidentresolution": { target: "teams", collection: false },
      },
      actions: {
      },
      functions: {
      },
    },
    "incidents": {
      properties: {
        "stageid": property("guid"),
        "entityimage_timestamp": property("number"),
        "coop_hr_vikarierarfor": property("string"),
        "coop_status_claims": property("number"),
        "coop_purchasingservicecasetype": property("number"),
        "coop_full_carrier_damaged": property("boolean"),
        "coop_everfresh_invoice_amount_state": property("number"),
        "coop_ordernumberportal": property("string"),
        "coop_invoiceflag2": property("number"),
        "coop_feedbackdate": property("datetimeoffset"),
        "coop_casestatus": property("number"),
        "coop_invoiceno": property("number"),
        "coop_hr_union_rep": property("string"),
        "coop_description": property("string"),
        "severitycode": property("number"),
        "coop_counterpartcomment": property("number"),
        "overriddencreatedon": property("datetimeoffset"),
        "coop_everfresh_category": property("number"),
        "coop_reason": property("string"),
        "coop_gtin": property("string"),
        "deactivatedon": property("datetimeoffset"),
        "coop_underlagsnummer": property("string"),
        "coop_numberofscannings_state": property("number"),
        "description": property("string"),
        "coop_sentclaimvalue": property("date"),
        "coop_isresovedcase": property("boolean"),
        "coop_numberofscannings_date": property("datetimeoffset"),
        "coop_hr_end_date_new": property("datetimeoffset"),
        "caseage": property("string"),
        "coop_testdescription": property("string"),
        "coop_hr_salary_supplement": property("string"),
        "coop_hrportalstatus": property("number"),
        "customercontacted": property("boolean"),
        "coop_invoicedatetocounterparty": property("datetimeoffset"),
        "coop_transportor2": property("number"),
        "coop_ordernumber": property("string"),
        "coop_bankcasetype": property("number"),
        "coop_expected_sol_date": property("datetimeoffset"),
        "coop_comment": property("number"),
        "coop_deviationdescriptionsv": property("string"),
        "coop_claimvalues": property("number"),
        "coop_resolvedon": property("datetimeoffset"),
        "coop_hr_cost_center": property("number"),
        "coop_importcaseasresolved": property("number"),
        "coop_dateintocomplaintresponsible": property("datetimeoffset"),
        "coop_cao_cause": property("number"),
        "lastinteraction": property("string"),
        "incidentstagecode": property("number"),
        "coop_othercomments": property("string"),
        "coop_coopgoodsvalues": property("number"),
        "coop_hr_description": property("string"),
        "coop_typeoftransportdamage": property("string"),
        "coop_goodsvalue": property("number"),
        "coop_forfallodatum": property("datetimeoffset"),
        "coop_kross_claim_value": property("number"),
        "coop_reminderrun": property("boolean"),
        "coop_md_approvalstatus": property("number"),
        "coop_hr_case_origin": property("number"),
        "servicestage": property("number"),
        "coop_hr_recruiters_managers_manager": property("string"),
        "coop_ldc": property("number"),
        "coop_cat_status": property("number"),
        "coop_senttocomplaintresponsible": property("boolean"),
        "coop_casenumbercarrier": property("string"),
        "coop_date": property("datetimeoffset"),
        "lastonholdtime": property("datetimeoffset"),
        "coop_alertstarttime": property("datetimeoffset"),
        "incidentid": property("key", { readonly: true }),
        "coop_noofrpu": property("number"),
        "coop_caseattachment": property("string"),
        "coop_hr_contact_email": property("string"),
        "coop_olderthan1day": property("boolean"),
        "checkemail": property("boolean"),
        "coop_hr_contact": property("string"),
        "coop_hascasebeenhandledbycustomerservice": property("boolean"),
        "coop_securityincidentnumber": property("string"),
        "coop_hr_recruitment_manager": property("string"),
        "coop_incidentdate": property("datetimeoffset"),
        "coop_resolution_status": property("number"),
        "coop_requesttype": property("number"),
        "coop_invoicedamount": property("number"),
        "coop_phonenumber": property("string"),
        "coop_notreportedtocarrier": property("boolean"),
        "coop_casemode": property("string"),
        "coop_caseforchange": property("boolean"),
        "coop_numberofscannings": property("number"),
        "sentimentvalue": property("number"),
        "coop_originalorderno": property("string"),
        "coop_abortallescalations": property("boolean"),
        "coop_feedbackby": property("number"),
        "traversedpath": property("string"),
        "coop_avvikelse_belopp_base": property("number"),
        "coop_deviationregisteredonfreightdocument": property("boolean"),
        "coop_measure": property("number"),
        "coop_fakturadifferens_base": property("number"),
        "coop_olderthan3days": property("boolean"),
        "coop_topparentcategory": property("string"),
        "coop_casesubmissioncomments": property("string"),
        "coop_category_cao_portal": property("number"),
        "coop_ateaticketnumber": property("string"),
        "coop_cs": property("string"),
        "coop_hr_discount_missing": property("string"),
        "coop_hr_rapporteringsstalle": property("string"),
        "coop_hr_deadline_application": property("datetimeoffset"),
        "coop_kross_claim_value_state": property("number"),
        "coop_deliverydate": property("datetimeoffset"),
        "coop_harkandidatenskttjnstenviajobylon": property("number"),
        "coop_bs_claimstatus": property("number"),
        "coop_arrivaldate": property("datetimeoffset"),
        "entityimageid": property("guid"),
        "coop_hr_company": property("string"),
        "coop_counterparty": property("string"),
        "coop_hr_personalnumber": property("string"),
        "coop_messagetosupplier": property("boolean"),
        "coop_pictureonthegoods": property("boolean"),
        "coop_isspecialeditable": property("boolean"),
        "coop_sscc": property("string"),
        "coop_datedecisioncomplaintresponsible": property("datetimeoffset"),
        "merged": property("boolean"),
        "statecode": property("number"),
        "coop_storenumber": property("string"),
        "nextsla": property("string"),
        "coop_hr_start_date": property("datetimeoffset"),
        "coop_depreciationpercent": property("number"),
        "coop_hr_desired_start_date": property("datetimeoffset"),
        "followuptaskcreated": property("boolean"),
        "timezoneruleversionnumber": property("number"),
        "coop_case_key": property("string"),
        "coop_hr_titel": property("string"),
        "coop_hr_position": property("string"),
        "coop_claimvalue": property("number"),
        "coop_closecasenotification": property("boolean"),
        "coop_hr_other_information": property("string"),
        "coop_hbokfnr": property("string"),
        "coop_deliverynotification": property("number"),
        "coop_isarticleassociated": property("number"),
        "coop_hr_orsaktillvikariat": property("string"),
        "coop_everfresh_invoice_amount_date": property("datetimeoffset"),
        "coop_olderthan5days": property("boolean"),
        "coop_levererandeterminal": property("number"),
        "coop_invoicenumber": property("string"),
        "actualserviceunits": property("number"),
        "coop_fakturadifferens": property("number"),
        "firstresponsesent": property("boolean"),
        "coop_lcd": property("string"),
        "decremententitlementterm": property("boolean"),
        "coop_vadgllerdittrende": property("number"),
        "coop_invoiceamount": property("number"),
        "coop_newcasenotification": property("boolean"),
        "coop_cause": property("number"),
        "routecase": property("boolean"),
        "exchangerate": property("number"),
        "coop_notes": property("string"),
        "coop_ateaflag": property("boolean"),
        "coop_harkandidatenfttinformationomattdetkommer": property("number"),
        "responseby": property("datetimeoffset"),
        "entityimage": property("binary"),
        "coop_lcdno": property("string"),
        "coop_actualdeliverydate": property("datetimeoffset"),
        "prioritycode": property("number"),
        "coop_hr_category": property("number"),
        "coop_load_carrier_id": property("string"),
        "coop_hr_enddate": property("datetimeoffset"),
        "coop_hr_employment_form": property("number"),
        "coop_fakturatotalbelopp_base": property("number"),
        "coop_otherexpense": property("number"),
        "followupby": property("datetimeoffset"),
        "coop_newlycreatedfromemail": property("boolean"),
        "coop_hr_employment_rate": property("number"),
        "resolveby": property("datetimeoffset"),
        "coop_descriptionwithouthtml": property("string"),
        "escalatedon": property("datetimeoffset"),
        "coop_hr_agreement": property("string"),
        "coop_hr_advertisement_length": property("number"),
        "coop_ai_status": property("number"),
        "coop_finance_complexity": property("number"),
        "emailaddress": property("string"),
        "coop_damaged_delivery": property("boolean"),
        "coop_hr_email_work": property("string"),
        "entityimage_url": property("string"),
        "coop_hr_contact_phone": property("string"),
        "coop_originatingqueue": property("string"),
        "coop_reasons": property("number"),
        "coop_terminal_location": property("number"),
        "coop_othercommentsmasterdata": property("string"),
        "coop_scannadpaterminal": property("number"),
        "blockedprofile": property("boolean"),
        "coop_errorsource": property("number"),
        "coop_resolution": property("string"),
        "isdecrementing": property("boolean"),
        "coop_flow2": property("number"),
        "coop_notifieddeliverydate": property("datetimeoffset"),
        "coop_goodsreceived": property("boolean"),
        "coop_claimdate": property("datetimeoffset"),
        "coop_olderthan7days": property("boolean"),
        "statuscode": property("number"),
        "coop_deviationdescription": property("string"),
        "billedserviceunits": property("number"),
        "processid": property("guid"),
        "coop_statusmasterdata": property("number"),
        "coop_invoiceflag": property("boolean"),
        "coop_fakturatotalbelopp": property("number"),
        "coop_counterpartylist": property("number"),
        "versionnumber": property("number"),
        "coop_saknarmedarbetarepersonalrabatt": property("number"),
        "numberofchildincidents": property("number"),
        "coop_hr_end_date": property("string"),
        "coop_klocaotype": property("boolean"),
        "coop_hr_selection_questions": property("string"),
        "coop_bankproduct": property("number"),
        "coop_category_bs_portal": property("number"),
        "ticketnumber": property("string"),
        "influencescore": property("number"),
        "coop_hr_medarbetarens_roll": property("number"),
        "utcconversiontimezonecode": property("number"),
        "coop_everfresh_invoice_amount": property("number"),
        "coop_flow": property("number"),
        "coop_bs_deviation_bill": property("boolean"),
        "onholdtime": property("number"),
        "createdon": property("datetimeoffset"),
        "coop_transportor1": property("number"),
        "coop_alerttrigger": property("boolean"),
        "coop_commentdepreciation": property("number"),
        "messagetypecode": property("number"),
        "activitiescomplete": property("boolean"),
        "coop_contactemailpreference": property("number"),
        "coop_contactperson": property("string"),
        "coop_category_autocomplete": property("string"),
        "coop_avvikelse_belopp": property("number"),
        "customersatisfactioncode": property("number"),
        "coop_kross_claim_value_date": property("datetimeoffset"),
        "casetypecode": property("number"),
        "caseorigincode": property("number"),
        "contractservicelevelcode": property("number"),
        "firstresponseslastatus": property("number"),
        "modifiedon": property("datetimeoffset"),
        "coop_regiontransport": property("number"),
        "coop_hr_contact_person": property("string"),
        "coop_case_cat_related": property("number"),
        "coop_region": property("number"),
        "coop_shippingnotenofonr": property("string"),
        "coop_storename": property("string"),
        "coop_hr_salary": property("string"),
        "isescalated": property("boolean"),
        "coop_caseregarding": property("number"),
        "coop_transport_cause": property("number"),
        "resolvebyslastatus": property("number"),
        "coop_decisioncomplaintresponsible": property("string"),
        "coop_handlahemmaordernumber": property("string"),
        "coop_storesupportcreditedshop": property("boolean"),
        "coop_fritext": property("string"),
        "coop_orsakskodtransportor": property("number"),
        "coop_otherexpenses": property("number"),
        "coop_soda_stream_quantity": property("number"),
        "coop_descriptionportal": property("string"),
        "coop_terminal": property("string"),
        "coop_categoryautocomplete": property("string"),
        "coop_kasearchstring": property("string"),
        "coop_deviationdescriptionen": property("string"),
        "coop_physicallysignedfreightdocument": property("boolean"),
        "coop_status": property("number"),
        "coop_tempnotification": property("number"),
        "coop_portalsubmissionchecker": property("string"),
        "coop_lcdnumber": property("number"),
        "coop_invoicerefno": property("string"),
        "coop_costreferencecoop": property("number"),
        "coop_hr_other_info": property("string"),
        "coop_terminalsolutiondescription": property("string"),
        "title": property("string"),
        "importsequencenumber": property("number"),
        "coop_waitingperiodforcheckclosecase": property("number"),
        "coop_invoiced": property("boolean"),
        "coop_goodsvalues": property("number"),
        "productserialnumber": property("string"),
      },
      navigations: {
        "Incident_Emails": { target: "emails", collection: true },
        "masterid": { target: "incidents", collection: false },
        "incident_master_incident": { target: "incidents", collection: true },
        "parentcaseid": { target: "incidents", collection: false },
        "incident_parent_incident": { target: "incidents", collection: true },
        "coop_Reporter": { target: "contacts", collection: false },
        "coop_ParentCase": { target: "incidents", collection: false },
        "coop_incident_incident_ParentCase": { target: "incidents", collection: true },
        "coop_previouscaseownerteam": { target: "teams", collection: false },
        "existingcase": { target: "incidents", collection: false },
        "incident_existingcase": { target: "incidents", collection: true },
        "owningteam": { target: "teams", collection: false },
        "customerid_contact": { target: "contacts", collection: false },
        "primarycontactid": { target: "contacts", collection: false },
        "responsiblecontactid": { target: "contacts", collection: false },
        "coop_relatedcaseuniqueid": { target: "incidents", collection: false },
        "coop_incident_incident": { target: "incidents", collection: true },
        "coop_CaseTeamId": { target: "teams", collection: false },
        "coop_webformsender": { target: "contacts", collection: false },
        "coop_incident_email_CaseforBSPortalEmail": { target: "emails", collection: true },
        "coop_RelatedCaseId": { target: "incidents", collection: false },
        "coop_transport_incident": { target: "incidents", collection: true },
        "coop_Contact": { target: "contacts", collection: false },
        "incident_activity_parties": { target: "activityparties", collection: true },
        "Incident_IncidentResolutions": { target: "incidentresolutions", collection: true },
        "Incident_ActivityPointers": { target: "activitypointers", collection: true },
      },
      actions: {
        "coop_CaseSendemailtoExpert": {
          scope: "entity",
          parameters: {
          },
          returnType: { target: "emails", collection: false },
        },
      },
      functions: {
        "CalculateTotalTimeIncident": {
          scope: "entity",
          parameters: {
          },
          returnType: { target: "CalculateTotalTimeIncidentResponse", collection: false },
        },
      },
    },
    "teams": {
      properties: {
        "membershiptype": property("number"),
        "isdefault": property("boolean"),
        "traversedpath": property("string"),
        "yominame": property("string"),
        "name": property("string"),
        "exchangerate": property("number"),
        "issastokenset": property("boolean"),
        "organizationid": property("guid"),
        "systemmanaged": property("boolean"),
        "importsequencenumber": property("number"),
        "versionnumber": property("number"),
        "description": property("string"),
        "emailaddress": property("string"),
        "processid": property("guid"),
        "teamtype": property("number"),
        "teamid": property("guid"),
        "overriddencreatedon": property("datetimeoffset"),
        "modifiedon": property("datetimeoffset"),
        "sharelinkqualifier": property("string"),
        "stageid": property("guid"),
        "createdon": property("datetimeoffset"),
        "azureactivedirectoryobjectid": property("guid"),
      },
      navigations: {
        "team_email": { target: "emails", collection: true },
        "team_contacts": { target: "contacts", collection: true },
        "team_activity": { target: "activitypointers", collection: true },
        "coop_team_incident_previouscaseownerteam": { target: "incidents", collection: true },
        "team_incidents": { target: "incidents", collection: true },
        "coop_team_incident": { target: "incidents", collection: true },
        "team_incidentresolution": { target: "incidentresolutions", collection: true },
      },
      actions: {
        "ConvertOwnerTeamToAccessTeam": {
          scope: "entity",
          parameters: {
          },
        },
        "SyncGroupMembersToTeam": {
          scope: "entity",
          parameters: {
          },
        },
      },
      functions: {
        "RetrievePrincipalAccess": {
          scope: "entity",
          parameters: {
        "Target": property("any" as any, { nullable: false }), // crmbaseentity
          },
          returnType: { target: "RetrievePrincipalAccessResponse", collection: false },
        },
        "RetrievePrincipalAccessInfo": {
          scope: "entity",
          parameters: {
        "ObjectId": property("guid", { nullable: false }),
        "EntityName": property("string", { nullable: false }),
          },
          returnType: { target: "RetrievePrincipalAccessInfoResponse", collection: false },
        },
        "RetrievePrincipalAttributePrivileges": {
          scope: "entity",
          parameters: {
          },
          returnType: { target: "RetrievePrincipalAttributePrivilegesResponse", collection: false },
        },
        "RetrievePrincipalSyncAttributeMappings": {
          scope: "entity",
          parameters: {
          },
          returnType: { target: "RetrievePrincipalSyncAttributeMappingsResponse", collection: false },
        },
        "RetrieveTeamPrivileges": {
          scope: "entity",
          parameters: {
          },
          returnType: { target: "RetrieveTeamPrivilegesResponse", collection: false },
        },
      },
    },
  },
  actions: {
        "_ResourcesRemoveUpdateAction": {
          useSchemaFQN: false,
          parameters: {
        "ResourcesToBeRemoved": property("string"),
        "ResourceGroupId": property("string"),
          },
        },
        "AddCertificateCredential": {
          useSchemaFQN: false,
          parameters: {
        "thumbprint": property("string", { nullable: false }),
        "entityLogicalName": property("string", { nullable: false }),
        "entityId": property("guid", { nullable: false }),
          },
        },
        "AutoMapEntity": {
          useSchemaFQN: false,
          parameters: {
        "EntityMapId": property("guid", { nullable: false }),
          },
        },
        "BotComponentFileCopy": {
          useSchemaFQN: false,
          parameters: {
        "botId": property("string", { nullable: false }),
        "mimeType": property("string", { nullable: false }),
        "fileName": property("string", { nullable: false }),
        "sourceBotComponentId": property("string", { nullable: false }),
        "targetBotComponentId": property("string", { nullable: false }),
          },
        },
        "cascadeAsync_SuccessAPI": {
          useSchemaFQN: false,
          parameters: {
        "casadeAsync_JobName": property("string", { nullable: false }),
          },
        },
        "cascadeAsyncSuccessAPI": {
          useSchemaFQN: false,
          parameters: {
        "casadeAsyncJobName": property("string", { nullable: false }),
          },
        },
        "cat_Sendfollowupemail": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "cat_Sendin-appnotification": {
          useSchemaFQN: false,
          parameters: {
        "ActionUrl": property("string", { nullable: false }),
        "ActionTitle": property("string", { nullable: false }),
        "Title": property("string", { nullable: false }),
        "Body": property("string", { nullable: false }),
        "Email": property("string", { nullable: false }),
          },
        },
        "CCaaS_CloseConversation": {
          useSchemaFQN: false,
          parameters: {
        "ActivityStatusCode": property("string", { nullable: false }),
        "LiveworkitemId": property("guid", { nullable: false }),
        "AgentId": property("guid", { nullable: false }),
          },
        },
        "CCaaS_ModifyAgentPresence": {
          useSchemaFQN: false,
          parameters: {
        "AgentId": property("guid", { nullable: false }),
        "ApiVersion": property("string", { nullable: false }),
        "PresenceId": property("guid", { nullable: false }),
          },
        },
        "CCaaS_SetPresence": {
          useSchemaFQN: false,
          parameters: {
        "PresenceId": property("guid", { nullable: false }),
        "ApiVersion": property("string", { nullable: false }),
          },
        },
        "cds_cascadeAsyncSuccessAPI": {
          useSchemaFQN: false,
          parameters: {
        "cds_casadeAsyncJobName": property("string", { nullable: false }),
          },
        },
        "CloseIncident": {
          useSchemaFQN: false,
          parameters: {
        "IncidentResolution": { target: "incidentresolutions", collection: false },
        "Status": property("number", { nullable: false }),
          },
        },
        "CreateAsyncJobToRevokeInheritedAccess": {
          useSchemaFQN: false,
          parameters: {
        "RelationshipSchema": property("string", { nullable: false }),
          },
        },
        "CreateNPSUserRating": {
          useSchemaFQN: false,
          parameters: {
        "Score": property("number", { nullable: false }),
        "Comment": property("string"),
        "AppModuleId": property("string", { nullable: false }),
        "Browser": property("string", { nullable: false }),
        "Device": property("string", { nullable: false }),
          },
        },
        "DeactivateEntityKey": {
          useSchemaFQN: false,
          parameters: {
        "EntityKeyLogicalName": property("string", { nullable: false }),
        "EntityLogicalName": property("string", { nullable: false }),
          },
        },
        "DeleteAutomatedPlugin": {
          useSchemaFQN: false,
          parameters: {
        "pluginid": property("string", { nullable: false }),
          },
        },
        "DeleteFile": {
          useSchemaFQN: false,
          parameters: {
        "FileId": property("guid", { nullable: false }),
          },
        },
        "DeleteInstantPlugin": {
          useSchemaFQN: false,
          parameters: {
        "FxExpressionUniqueName": property("string", { nullable: false }),
          },
        },
        "DeleteOptionValue": {
          useSchemaFQN: false,
          parameters: {
        "OptionSetName": property("string"),
        "AttributeLogicalName": property("string"),
        "EntityLogicalName": property("string"),
        "Value": property("number", { nullable: false }),
        "SolutionUniqueName": property("string"),
          },
        },
        "DeleteOQOILineWithSkipPricingCalculation": {
          useSchemaFQN: false,
          parameters: {
        "entityLogicalName": property("string", { nullable: false }),
        "entityId": property("guid", { nullable: false }),
          },
        },
        "DeprovisionLanguage": {
          useSchemaFQN: false,
          parameters: {
        "Language": property("number", { nullable: false }),
          },
        },
        "GrantAccessUsingSharedLink": {
          useSchemaFQN: false,
          parameters: {
        "RecordUrlWithSharedLink": property("string", { nullable: false }),
          },
        },
        "ImportSolutions": {
          useSchemaFQN: false,
          parameters: {
        "OverwriteUnmanagedCustomizations": property("boolean", { nullable: false }),
        "PublishWorkflows": property("boolean", { nullable: false }),
        "CustomizationFiles": property("binary", { nullable: false }),
        "ImportJobId": property("guid", { nullable: false }),
        "ConvertToManaged": property("boolean"),
        "SkipProductUpdateDependencies": property("boolean"),
        "HoldingSolution": property("boolean"),
          },
        },
        "ImportTranslation": {
          useSchemaFQN: false,
          parameters: {
        "TranslationFile": property("binary", { nullable: false }),
        "ImportJobId": property("guid", { nullable: false }),
          },
        },
        "InstallSampleData": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "msdynmkt_GetPublicConfigurationCustomAction": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "msdynmkt_PredefinedPlaceholderAddCount": {
          useSchemaFQN: false,
          parameters: {
        "PredefinedPlaceholderAddCountRequest": property("string"),
          },
        },
        "none_RemoveMarketingListMembersByIds": {
          useSchemaFQN: false,
          parameters: {
        "ListId": property("string"),
        "MemberIds": property("string"),
          },
        },
        "NotifyEnvironmentVariableSecretChange": {
          useSchemaFQN: false,
          parameters: {
        "KeyVaultUrl": property("string", { nullable: false }),
        "SecretName": property("string", { nullable: false }),
          },
        },
        "OrderOption": {
          useSchemaFQN: false,
          parameters: {
        "OptionSetName": property("string"),
        "AttributeLogicalName": property("string"),
        "EntityLogicalName": property("string"),
        "Values": property("number", { collection: true, nullable: false }),
        "SolutionUniqueName": property("string"),
          },
        },
        "ProvisionLanguage": {
          useSchemaFQN: false,
          parameters: {
        "Language": property("number", { nullable: false }),
          },
        },
        "PublishAllXml": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "PublishXml": {
          useSchemaFQN: false,
          parameters: {
        "ParameterXml": property("string", { nullable: false }),
          },
        },
        "QueueUpdateRibbonClientMetadata": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "ReactivateEntityKey": {
          useSchemaFQN: false,
          parameters: {
        "EntityKeyLogicalName": property("string", { nullable: false }),
        "EntityLogicalName": property("string", { nullable: false }),
          },
        },
        "RecalculatePrice": {
          useSchemaFQN: false,
          parameters: {
        "entityLogicalName": property("string", { nullable: false }),
        "entityId": property("guid", { nullable: false }),
          },
        },
        "RemoveCertificateCredential": {
          useSchemaFQN: false,
          parameters: {
        "entityId": property("guid", { nullable: false }),
        "entityLogicalName": property("string", { nullable: false }),
        "certificateCredentialId": property("guid"),
          },
        },
        "ResetUserFilters": {
          useSchemaFQN: false,
          parameters: {
        "QueryType": property("number", { nullable: false }),
          },
        },
        "SaveSettingValue": {
          useSchemaFQN: false,
          parameters: {
        "AppUniqueName": property("string"),
        "SettingName": property("string", { nullable: false }),
        "Value": property("string", { nullable: false }),
        "SolutionUniqueName": property("string"),
          },
        },
        "SendFax": {
          useSchemaFQN: false,
          parameters: {
        "FaxId": property("guid", { nullable: false }),
        "IssueSend": property("boolean", { nullable: false }),
          },
        },
        "SetAutoNumberSeed": {
          useSchemaFQN: false,
          parameters: {
        "EntityName": property("string", { nullable: false }),
        "AttributeName": property("string", { nullable: false }),
        "Value": property("number", { nullable: false }),
          },
        },
        "SetBusinessEquipment": {
          useSchemaFQN: false,
          parameters: {
        "EquipmentId": property("guid", { nullable: false }),
        "BusinessUnitId": property("guid", { nullable: false }),
          },
        },
        "SetDataEncryptionKey": {
          useSchemaFQN: false,
          parameters: {
        "EncryptionKey": property("string", { nullable: false }),
        "ChangeEncryptionKey": property("boolean", { nullable: false }),
          },
        },
        "SetFeatureStatus": {
          useSchemaFQN: false,
          parameters: {
        "FeatureType": property("number", { nullable: false }),
        "Status": property("boolean", { nullable: false }),
        "ConfigData": property("string"),
        "IsSolutionUninstall": property("boolean"),
          },
        },
        "SetPreferredSolution": {
          useSchemaFQN: false,
          parameters: {
        "SolutionId": property("guid", { nullable: false }),
          },
        },
        "SetReportRelated": {
          useSchemaFQN: false,
          parameters: {
        "ReportId": property("guid", { nullable: false }),
        "Entities": property("number", { collection: true, nullable: false }),
        "Categories": property("number", { collection: true, nullable: false }),
        "Visibility": property("number", { collection: true, nullable: false }),
          },
        },
        "UninstallSampleData": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "UninstallSolution": {
          useSchemaFQN: false,
          parameters: {
        "SolutionUniqueName": property("string", { nullable: false }),
          },
        },
        "UnlockInvoicePricing": {
          useSchemaFQN: false,
          parameters: {
        "InvoiceId": property("guid", { nullable: false }),
          },
        },
        "UnlockSalesOrderPricing": {
          useSchemaFQN: false,
          parameters: {
        "SalesOrderId": property("guid", { nullable: false }),
          },
        },
        "UnpublishDuplicateRule": {
          useSchemaFQN: false,
          parameters: {
        "DuplicateRuleId": property("guid", { nullable: false }),
          },
        },
        "UpdateAutomatedPlugin": {
          useSchemaFQN: false,
          parameters: {
        "Name": property("string"),
        "SolutionUniqueName": property("string"),
        "EntityLogicalName": property("string"),
        "Expression": property("string"),
        "Stage": property("number"),
        "FxExpressionUniqueName": property("string", { nullable: false }),
        "MessageName": property("string"),
        "Context": property("string"),
          },
        },
        "UpdateFeatureConfig": {
          useSchemaFQN: false,
          parameters: {
        "FeatureType": property("number", { nullable: false }),
        "ConfigData": property("string", { nullable: false }),
          },
        },
        "UpdateInstantPlugin": {
          useSchemaFQN: false,
          parameters: {
        "FxExpressionUniqueName": property("string", { nullable: false }),
        "Parameters": property("string"),
        "EntityLogicalName": property("string"),
        "Name": property("string"),
        "SolutionUniqueName": property("string"),
        "Expression": property("string"),
        "Description": property("string"),
        "Context": property("string"),
          },
        },
        "UpdateRibbonClientMetadata": {
          useSchemaFQN: false,
          parameters: {
          },
        },
        "UpdateSolutionComponent": {
          useSchemaFQN: false,
          parameters: {
        "ComponentId": property("guid", { nullable: false }),
        "ComponentType": property("number", { nullable: false }),
        "SolutionUniqueName": property("string", { nullable: false }),
        "IncludedComponentSettingsValues": property("string", { collection: true }),
          },
        },
        "UploadBlock": {
          useSchemaFQN: false,
          parameters: {
        "BlockId": property("string", { nullable: false }),
        "BlockData": property("binary", { nullable: false }),
        "FileContinuationToken": property("string", { nullable: false }),
          },
        },
        "UpsertCompositeDataSource": {
          useSchemaFQN: false,
          parameters: {
        "ParentDisplayName": property("string"),
        "ParentSchemaName": property("string", { nullable: false }),
        "ParentParameterKey": property("string", { nullable: false }),
        "ParentApiId": property("string"),
        "ParentValue": property("string"),
        "ChildDisplayName": property("string"),
        "ChildSchemaName": property("string"),
        "ChildParameterKey": property("string"),
        "ChildValue": property("string"),
          },
        },
        "UpsertEnvironmentVariable": {
          useSchemaFQN: false,
          parameters: {
        "DisplayName": property("string"),
        "SchemaName": property("string", { nullable: false }),
        "Type": property("number", { nullable: false }),
        "DefaultValue": property("string"),
        "Value": property("string"),
        "SecretStore": property("number"),
        "ParameterKey": property("string"),
        "ApiId": property("string"),
          },
        },
  },
  functions: {
        "In": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValues": property("string", { collection: true, nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NotIn": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValues": property("string", { collection: true, nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Between": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValues": property("string", { collection: true, nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NotBetween": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValues": property("string", { collection: true, nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Yesterday": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Today": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Tomorrow": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Last7Days": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Next7Days": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastWeek": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "ThisWeek": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextWeek": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastMonth": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "ThisMonth": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextMonth": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "On": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OnOrBefore": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OnOrAfter": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "ThisYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXHours": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXHours": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXDays": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXDays": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXWeeks": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXWeeks": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXMonths": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXMonths": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXYears": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXYears": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualUserId": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NotEqualUserId": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualBusinessId": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NotEqualBusinessId": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Contains": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualUserLanguage": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OlderThanXMonths": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "ThisFiscalYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "ThisFiscalPeriod": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextFiscalYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextFiscalPeriod": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastFiscalYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastFiscalPeriod": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXFiscalYears": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "LastXFiscalPeriods": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXFiscalYears": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NextXFiscalPeriods": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "InFiscalYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "InFiscalPeriod": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "InFiscalPeriodAndYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue1": property("number", { nullable: false }),
        "PropertyValue2": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "InOrBeforeFiscalPeriodAndYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue1": property("number", { nullable: false }),
        "PropertyValue2": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "InOrAfterFiscalPeriodAndYear": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue1": property("number", { nullable: false }),
        "PropertyValue2": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualUserTeams": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualUserOrUserTeams": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Under": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "NotUnder": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "UnderOrEqual": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "Above": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "AboveOrEqual": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualUserOrUserHierarchy": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualUserOrUserHierarchyAndTeams": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OlderThanXYears": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OlderThanXWeeks": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OlderThanXDays": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OlderThanXHours": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "OlderThanXMinutes": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValue": property("number", { nullable: false }),
          },
          returnType: property("boolean"),
        },
        "ContainValues": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValues": property("string", { collection: true, nullable: false }),
          },
          returnType: property("boolean"),
        },
        "DoesNotContainValues": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
        "PropertyValues": property("string", { collection: true, nullable: false }),
          },
          returnType: property("boolean"),
        },
        "EqualRoleBusinessId": {
          useSchemaFQN: false,
          parameters: {
        "PropertyName": property("string", { nullable: false }),
          },
          returnType: property("boolean"),
        },
  },
});
